# 뉴스 검증하기 위해서 사용하는 코드
과거 뉴스 스크랩 한 뒤 상승 하락 칼럼 만들고 뉴스 본문 요약 후 쪼개서 감정분석

In [1]:
import pandas as pd
from google.colab import drive
\
# 1. 구글 드라이브 마운트
drive.mount('/content/drive')
dfdf = pd.read_csv("/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/newstest.csv")
df = dfdf.copy()

Mounted at /content/drive

In [2]:
df = df.sample(n=1000, random_state=42).reset_index(drop=True)

In [3]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
import pandas as pd

# ✅ 모델 로딩
model_name = "facebook/bart-large-cnn"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name, use_safetensors=True)
summarizer = pipeline("summarization", model=model, tokenizer=tokenizer)

# ✅ 긴 본문 자동 분할 요약 함수
def summarize_text(text, max_chunk_tokens=900):
    inputs = tokenizer(text, return_tensors="pt", truncation=False)
    input_ids = inputs["input_ids"][0]
    total_tokens = len(input_ids)

    if total_tokens <= max_chunk_tokens:
        return summarizer(text, max_length=100, min_length=20, do_sample=False)[0]["summary_text"]

    summaries = []
    for i in range(0, total_tokens, max_chunk_tokens):
        chunk_ids = input_ids[i:i + max_chunk_tokens]
        chunk_text = tokenizer.decode(chunk_ids, skip_special_tokens=True)
        summary = summarizer(chunk_text, max_length=80, min_length=15, do_sample=False)[0]["summary_text"]
        summaries.append(summary)

    return " ".join(summaries)

# ✅ DataFrame 불러오기 및 요약 칼럼 추가
# df = pd.read_csv("your_file.csv")  # 필요 시 주석 해제
summaries = []

for i, text in enumerate(df["본문"]):
    try:
        summary = summarize_text(text)
        print(f"[{i}번째 진g")
    except Exception as e:
        print(f"[{i}번째 요약 실패] {e}")
        summary = "[요약 실패]"
    summaries.append(summary)

df["요약"] = summaries

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Device set to use cuda:0

[0번째 진g
[1번째 진g
[2번째 진g
[3번째 진g

Your max_length is set to 100, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[4번째 진g
[5번째 진g

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[6번째 진g
[7번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[8번째 진g
[9번째 진g
[10번째 진g

Your max_length is set to 80, but your input_length is only 78. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=39)

[11번째 진g
[12번째 진g
[13번째 진g
[14번째 진g
[15번째 진g
[16번째 진g
[17번째 진g
[18번째 진g
[19번째 진g
[20번째 진g
[21번째 진g
[22번째 진g
[23번째 진g
[24번째 진g
[25번째 진g
[26번째 진g
[27번째 진g
[28번째 진g
[29번째 진g
[30번째 진g
[31번째 진g

Your max_length is set to 100, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[32번째 진g
[33번째 진g
[34번째 진g
[35번째 진g
[36번째 진g
[37번째 진g
[38번째 진g
[39번째 진g
[40번째 진g
[41번째 진g
[42번째 진g
[43번째 진g
[44번째 진g
[45번째 진g
[46번째 진g
[47번째 진g
[48번째 진g

Your max_length is set to 100, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[49번째 진g
[50번째 진g
[51번째 진g

Your max_length is set to 80, but your input_length is only 19. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=9)

[52번째 진g
[53번째 진g
[54번째 진g

Your max_length is set to 80, but your input_length is only 57. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=28)

[55번째 진g
[56번째 진g
[57번째 진g
[58번째 진g
[59번째 진g
[60번째 진g
[61번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[62번째 진g
[63번째 진g
[64번째 진g

Your max_length is set to 80, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[65번째 진g
[66번째 진g
[67번째 진g
[68번째 진g
[69번째 진g
[70번째 진g
[71번째 진g
[72번째 진g
[73번째 진g

Your max_length is set to 80, but your input_length is only 9. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=4)

[74번째 진g

Your max_length is set to 100, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[75번째 진g
[76번째 진g
[77번째 진g

Your max_length is set to 100, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[78번째 진g
[79번째 진g
[80번째 진g
[81번째 진g
[82번째 진g
[83번째 진g
[84번째 진g
[85번째 진g
[86번째 진g
[87번째 진g
[88번째 진g
[89번째 진g
[90번째 진g
[91번째 진g
[92번째 진g
[93번째 진g
[94번째 진g

Your max_length is set to 80, but your input_length is only 67. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=33)

[95번째 진g

Your max_length is set to 80, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[96번째 진g
[97번째 진g
[98번째 진g
[99번째 진g
[100번째 진g
[101번째 진g
[102번째 진g
[103번째 진g
[104번째 진g
[105번째 진g
[106번째 진g

Your max_length is set to 80, but your input_length is only 3. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=1)

[107번째 진g

Your max_length is set to 80, but your input_length is only 47. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=23)

[108번째 진g
[109번째 진g
[110번째 진g
[111번째 진g
[112번째 진g
[113번째 진g
[114번째 진g
[115번째 진g
[116번째 진g
[117번째 진g
[118번째 진g
[119번째 진g
[120번째 진g
[121번째 진g
[122번째 진g
[123번째 진g

Your max_length is set to 80, but your input_length is only 16. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=8)

[124번째 진g
[125번째 진g
[126번째 진g
[127번째 진g
[128번째 진g
[129번째 진g
[130번째 진g
[131번째 진g
[132번째 진g
[133번째 진g
[134번째 진g
[135번째 진g
[136번째 진g
[137번째 진g
[138번째 진g
[139번째 진g

Your max_length is set to 100, but your input_length is only 28. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)

[140번째 진g
[141번째 진g
[142번째 진g
[143번째 진g

Your max_length is set to 100, but your input_length is only 28. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)

[144번째 진g
[145번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[146번째 진g
[147번째 진g
[148번째 진g
[149번째 진g
[150번째 진g
[151번째 진g

Your max_length is set to 80, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[152번째 진g
[153번째 진g
[154번째 진g
[155번째 진g
[156번째 진g
[157번째 진g
[158번째 진g
[159번째 진g
[160번째 진g
[161번째 진g
[162번째 진g
[163번째 진g
[164번째 진g

Your max_length is set to 100, but your input_length is only 76. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=38)

[165번째 진g
[166번째 진g
[167번째 진g
[168번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[169번째 진g
[170번째 진g
[171번째 진g
[172번째 진g

Your max_length is set to 80, but your input_length is only 12. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=6)

[173번째 진g
[174번째 진g
[175번째 진g
[176번째 진g
[177번째 진g
[178번째 진g
[179번째 진g
[180번째 진g
[181번째 진g
[182번째 진g
[183번째 진g
[184번째 진g
[185번째 진g
[186번째 진g
[187번째 진g
[188번째 진g
[189번째 진g
[190번째 진g
[191번째 진g

Your max_length is set to 80, but your input_length is only 64. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=32)

[192번째 진g
[193번째 진g
[194번째 진g
[195번째 진g
[196번째 진g
[197번째 진g
[198번째 진g
[199번째 진g
[200번째 진g
[201번째 진g

Your max_length is set to 100, but your input_length is only 22. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[202번째 진g
[203번째 진g
[204번째 진g

Your max_length is set to 100, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[205번째 진g
[206번째 진g
[207번째 진g
[208번째 진g
[209번째 진g
[210번째 진g
[211번째 진g
[212번째 진g
[213번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[214번째 진g
[215번째 진g
[216번째 진g
[217번째 진g
[218번째 진g
[219번째 진g
[220번째 진g
[221번째 진g
[222번째 진g
[223번째 진g

Your max_length is set to 100, but your input_length is only 28. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)

[224번째 진g
[225번째 진g
[226번째 진g
[227번째 진g

Your max_length is set to 80, but your input_length is only 50. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=25)

[228번째 진g
[229번째 진g
[230번째 진g
[231번째 진g
[232번째 진g
[233번째 진g
[234번째 진g
[235번째 진g
[236번째 진g
[237번째 진g
[238번째 진g

Your max_length is set to 80, but your input_length is only 33. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=16)

[239번째 진g
[240번째 진g
[241번째 진g
[242번째 진g
[243번째 진g

Your max_length is set to 80, but your input_length is only 70. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=35)

[244번째 진g

Your max_length is set to 80, but your input_length is only 74. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=37)

[245번째 진g
[246번째 진g
[247번째 진g
[248번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[249번째 진g

Your max_length is set to 100, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[250번째 진g
[251번째 진g
[252번째 진g

Your max_length is set to 80, but your input_length is only 20. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[253번째 진g
[254번째 진g
[255번째 진g
[256번째 진g

Your max_length is set to 100, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[257번째 진g
[258번째 진g
[259번째 진g
[260번째 진g
[261번째 진g
[262번째 진g
[263번째 진g
[264번째 진g
[265번째 진g
[266번째 진g
[267번째 진g
[268번째 진g

Your max_length is set to 100, but your input_length is only 33. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=16)

[269번째 진g
[270번째 진g
[271번째 진g
[272번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[273번째 진g
[274번째 진g
[275번째 진g
[276번째 진g
[277번째 진g
[278번째 진g
[279번째 진g
[280번째 진g

Your max_length is set to 100, but your input_length is only 79. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=39)

[281번째 진g
[282번째 진g
[283번째 진g
[284번째 진g
[285번째 진g
[286번째 진g
[287번째 진g
[288번째 진g
[289번째 진g
[290번째 진g
[291번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[292번째 진g
[293번째 진g

Your max_length is set to 100, but your input_length is only 41. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=20)

[294번째 진g
[295번째 진g
[296번째 진g
[297번째 진g

Your max_length is set to 100, but your input_length is only 38. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=19)

[298번째 진g
[299번째 진g
[300번째 진g
[301번째 진g
[302번째 진g
[303번째 진g
[304번째 진g
[305번째 진g
[306번째 진g

Your max_length is set to 100, but your input_length is only 21. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[307번째 진g
[308번째 진g
[309번째 진g
[310번째 진g
[311번째 진g
[312번째 진g
[313번째 진g
[314번째 진g
[315번째 진g

Your max_length is set to 100, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[316번째 진g
[317번째 진g
[318번째 진g
[319번째 진g
[320번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[321번째 진g
[322번째 진g
[323번째 진g

Your max_length is set to 80, but your input_length is only 16. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=8)

[324번째 진g

Your max_length is set to 80, but your input_length is only 36. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=18)

[325번째 진g
[326번째 진g
[327번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[328번째 진g
[329번째 진g
[330번째 진g
[331번째 진g

Your max_length is set to 80, but your input_length is only 3. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=1)

[332번째 진g
[333번째 진g
[334번째 진g

Your max_length is set to 80, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[335번째 진g
[336번째 진g
[337번째 진g
[338번째 진g
[339번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[340번째 진g
[341번째 진g
[342번째 진g
[343번째 진g
[344번째 진g

Your max_length is set to 80, but your input_length is only 78. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=39)

[345번째 진g
[346번째 진g
[347번째 진g
[348번째 진g
[349번째 진g
[350번째 진g
[351번째 진g
[352번째 진g
[353번째 진g

Your max_length is set to 100, but your input_length is only 85. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=42)

[354번째 진g
[355번째 진g
[356번째 진g
[357번째 진g
[358번째 진g
[359번째 진g
[360번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[361번째 진g
[362번째 진g
[363번째 진g
[364번째 진g
[365번째 진g
[366번째 진g
[367번째 진g
[368번째 진g
[369번째 진g
[370번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[371번째 진g
[372번째 진g
[373번째 진g
[374번째 진g
[375번째 진g
[376번째 진g
[377번째 진g
[378번째 진g
[379번째 진g
[380번째 진g
[381번째 진g
[382번째 진g
[383번째 진g
[384번째 진g
[385번째 진g
[386번째 진g
[387번째 진g
[388번째 진g
[389번째 진g
[390번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[391번째 진g

Your max_length is set to 100, but your input_length is only 54. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=27)

[392번째 진g
[393번째 진g
[394번째 진g
[395번째 진g
[396번째 진g
[397번째 진g
[398번째 진g
[399번째 진g
[400번째 진g

Your max_length is set to 80, but your input_length is only 72. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=36)

[401번째 진g

Your max_length is set to 80, but your input_length is only 62. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=31)
Your max_length is set to 100, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[402번째 진g
[403번째 진g
[404번째 진g
[405번째 진g
[406번째 진g
[407번째 진g
[408번째 진g
[409번째 진g
[410번째 진g
[411번째 진g
[412번째 진g
[413번째 진g
[414번째 진g
[415번째 진g

Your max_length is set to 80, but your input_length is only 74. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=37)

[416번째 진g
[417번째 진g
[418번째 진g
[419번째 진g
[420번째 진g
[421번째 진g
[422번째 진g
[423번째 진g
[424번째 진g
[425번째 진g
[426번째 진g
[427번째 진g
[428번째 진g
[429번째 진g

Your max_length is set to 80, but your input_length is only 64. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=32)

[430번째 진g
[431번째 진g
[432번째 진g
[433번째 진g
[434번째 진g
[435번째 진g
[436번째 진g
[437번째 진g
[438번째 진g

Your max_length is set to 80, but your input_length is only 45. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=22)

[439번째 진g
[440번째 진g
[441번째 진g
[442번째 진g
[443번째 진g

Your max_length is set to 80, but your input_length is only 21. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[444번째 진g
[445번째 진g
[446번째 진g

Your max_length is set to 100, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[447번째 진g
[448번째 진g
[449번째 진g

Your max_length is set to 80, but your input_length is only 8. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=4)

[450번째 진g
[451번째 진g
[452번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[453번째 진g
[454번째 진g
[455번째 진g
[456번째 진g
[457번째 진g
[458번째 진g
[459번째 진g

Your max_length is set to 100, but your input_length is only 21. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[460번째 진g
[461번째 진g
[462번째 진g
[463번째 진g

Your max_length is set to 80, but your input_length is only 61. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=30)

[464번째 진g
[465번째 진g
[466번째 진g
[467번째 진g
[468번째 진g
[469번째 진g
[470번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[471번째 진g
[472번째 진g
[473번째 진g
[474번째 진g
[475번째 진g
[476번째 진g
[477번째 진g

Your max_length is set to 100, but your input_length is only 90. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=45)

[478번째 진g
[479번째 진g
[480번째 진g
[481번째 진g
[482번째 진g
[483번째 진g
[484번째 진g
[485번째 진g
[486번째 진g
[487번째 진g
[488번째 진g
[489번째 진g
[490번째 진g
[491번째 진g
[492번째 진g

Your max_length is set to 80, but your input_length is only 71. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=35)

[493번째 진g
[494번째 진g
[495번째 진g
[496번째 진g
[497번째 진g
[498번째 진g
[499번째 진g
[500번째 진g
[501번째 진g

Your max_length is set to 100, but your input_length is only 71. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=35)

[502번째 진g

Your max_length is set to 100, but your input_length is only 30. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=15)

[503번째 진g
[504번째 진g
[505번째 진g
[506번째 진g
[507번째 진g
[508번째 진g
[509번째 진g

Your max_length is set to 100, but your input_length is only 20. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[510번째 진g
[511번째 진g
[512번째 진g
[513번째 진g
[514번째 진g
[515번째 진g
[516번째 진g
[517번째 진g
[518번째 진g
[519번째 진g
[520번째 진g
[521번째 진g
[522번째 진g

Your max_length is set to 80, but your input_length is only 6. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=3)

[523번째 진g
[524번째 진g
[525번째 진g
[526번째 진g
[527번째 진g
[528번째 진g
[529번째 진g
[530번째 진g
[531번째 진g
[532번째 진g
[533번째 진g
[534번째 진g
[535번째 진g
[536번째 진g
[537번째 진g
[538번째 진g
[539번째 진g
[540번째 진g
[541번째 진g
[542번째 진g
[543번째 진g
[544번째 진g
[545번째 진g

Your max_length is set to 80, but your input_length is only 17. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=8)

[546번째 진g
[547번째 진g
[548번째 진g
[549번째 진g
[550번째 진g
[551번째 진g
[552번째 진g
[553번째 진g
[554번째 진g
[555번째 진g
[556번째 진g
[557번째 진g
[558번째 진g
[559번째 진g

Your max_length is set to 100, but your input_length is only 30. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=15)

[560번째 진g
[561번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[562번째 진g
[563번째 진g
[564번째 진g
[565번째 진g
[566번째 진g
[567번째 진g

Your max_length is set to 80, but your input_length is only 52. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=26)

[568번째 진g
[569번째 진g

Your max_length is set to 80, but your input_length is only 31. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=15)
Your max_length is set to 100, but your input_length is only 86. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=43)

[570번째 진g
[571번째 진g
[572번째 진g
[573번째 진g
[574번째 진g
[575번째 진g
[576번째 진g
[577번째 진g
[578번째 진g
[579번째 진g
[580번째 진g
[581번째 진g
[582번째 진g

Your max_length is set to 80, but your input_length is only 9. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=4)

[583번째 진g

Your max_length is set to 80, but your input_length is only 20. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)
Your max_length is set to 100, but your input_length is only 58. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=29)

[584번째 진g
[585번째 진g
[586번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

Your max_length is set to 80, but your input_length is only 77. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=38)

[587번째 진g
[588번째 진g
[589번째 진g
[590번째 진g
[591번째 진g
[592번째 진g
[593번째 진g
[594번째 진g
[595번째 진g
[596번째 진g
[597번째 진g
[598번째 진g
[599번째 진g
[600번째 진g

Your max_length is set to 80, but your input_length is only 40. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=20)

[601번째 진g
[602번째 진g
[603번째 진g
[604번째 진g
[605번째 진g
[606번째 진g
[607번째 진g
[608번째 진g
[609번째 진g
[610번째 진g
[611번째 진g
[612번째 진g
[613번째 진g
[614번째 진g
[615번째 진g
[616번째 진g
[617번째 진g
[618번째 진g
[619번째 진g
[620번째 진g
[621번째 진g
[622번째 진g
[623번째 진g
[624번째 진g
[625번째 진g
[626번째 진g
[627번째 진g
[628번째 진g
[629번째 진g
[630번째 진g
[631번째 진g
[632번째 진g
[633번째 진g
[634번째 진g

Your max_length is set to 80, but your input_length is only 8. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=4)
Your max_length is set to 100, but your input_length is only 32. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=16)

[635번째 진g
[636번째 진g
[637번째 진g
[638번째 진g
[639번째 진g
[640번째 진g
[641번째 진g
[642번째 진g
[643번째 진g
[644번째 진g

Your max_length is set to 100, but your input_length is only 67. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=33)

[645번째 진g

Your max_length is set to 100, but your input_length is only 33. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=16)

[646번째 진g
[647번째 진g
[648번째 진g
[649번째 진g

Your max_length is set to 80, but your input_length is only 51. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=25)

[650번째 진g
[651번째 진g
[652번째 진g
[653번째 진g
[654번째 진g
[655번째 진g
[656번째 진g
[657번째 진g
[658번째 진g
[659번째 진g
[660번째 진g
[661번째 진g
[662번째 진g

Your max_length is set to 100, but your input_length is only 80. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=40)

[663번째 진g
[664번째 진g
[665번째 진g
[666번째 진g
[667번째 진g
[668번째 진g
[669번째 진g
[670번째 진g
[671번째 진g

Your max_length is set to 80, but your input_length is only 72. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=36)

[672번째 진g
[673번째 진g
[674번째 진g
[675번째 진g
[676번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[677번째 진g
[678번째 진g
[679번째 진g
[680번째 진g
[681번째 진g

Your max_length is set to 80, but your input_length is only 42. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=21)

[682번째 진g
[683번째 진g
[684번째 진g
[685번째 진g
[686번째 진g
[687번째 진g
[688번째 진g
[689번째 진g
[690번째 진g
[691번째 진g
[692번째 진g
[693번째 진g
[694번째 진g
[695번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[696번째 진g
[697번째 진g
[698번째 진g
[699번째 진g
[700번째 진g
[701번째 진g
[702번째 진g
[703번째 진g
[704번째 진g
[705번째 진g
[706번째 진g
[707번째 진g
[708번째 진g

Your max_length is set to 100, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[709번째 진g
[710번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[711번째 진g
[712번째 진g
[713번째 진g
[714번째 진g
[715번째 진g
[716번째 진g

Your max_length is set to 100, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[717번째 진g
[718번째 진g
[719번째 진g
[720번째 진g
[721번째 진g
[722번째 진g
[723번째 진g
[724번째 진g

Your max_length is set to 80, but your input_length is only 11. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=5)

[725번째 진g
[726번째 진g
[727번째 진g
[728번째 진g
[729번째 진g

Your max_length is set to 100, but your input_length is only 30. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=15)

[730번째 진g
[731번째 진g
[732번째 진g
[733번째 진g
[734번째 진g
[735번째 진g
[736번째 진g
[737번째 진g
[738번째 진g
[739번째 진g

Your max_length is set to 100, but your input_length is only 50. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=25)

[740번째 진g
[741번째 진g
[742번째 진g

Your max_length is set to 100, but your input_length is only 29. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)

[743번째 진g
[744번째 진g
[745번째 진g
[746번째 진g
[747번째 진g
[748번째 진g

Your max_length is set to 100, but your input_length is only 84. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=42)

[749번째 진g
[750번째 진g
[751번째 진g

Your max_length is set to 100, but your input_length is only 68. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=34)

[752번째 진g
[753번째 진g
[754번째 진g
[755번째 진g

Your max_length is set to 80, but your input_length is only 3. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=1)

[756번째 진g
[757번째 진g
[758번째 진g
[759번째 진g

Your max_length is set to 100, but your input_length is only 35. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=17)

[760번째 진g
[761번째 진g
[762번째 진g
[763번째 진g
[764번째 진g
[765번째 진g
[766번째 진g
[767번째 진g
[768번째 진g
[769번째 진g
[770번째 진g
[771번째 진g
[772번째 진g
[773번째 진g
[774번째 진g
[775번째 진g
[776번째 진g
[777번째 진g
[778번째 진g

Your max_length is set to 80, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[779번째 진g
[780번째 진g
[781번째 진g
[782번째 진g
[783번째 진g
[784번째 요약 실패] text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
[785번째 진g
[786번째 진g
[787번째 진g
[788번째 진g
[789번째 진g
[790번째 진g
[791번째 진g
[792번째 진g

Your max_length is set to 100, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[793번째 진g
[794번째 진g
[795번째 진g
[796번째 진g
[797번째 진g
[798번째 진g
[799번째 진g
[800번째 진g
[801번째 진g
[802번째 진g
[803번째 진g
[804번째 진g

Your max_length is set to 80, but your input_length is only 20. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[805번째 진g
[806번째 진g
[807번째 진g
[808번째 진g

Your max_length is set to 80, but your input_length is only 39. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=19)

[809번째 진g
[810번째 진g
[811번째 진g
[812번째 진g
[813번째 진g

Your max_length is set to 80, but your input_length is only 11. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=5)

[814번째 진g

Your max_length is set to 80, but your input_length is only 33. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=16)

[815번째 진g
[816번째 진g
[817번째 진g
[818번째 진g
[819번째 진g
[820번째 진g
[821번째 진g
[822번째 진g
[823번째 진g
[824번째 진g
[825번째 진g
[826번째 진g
[827번째 진g
[828번째 진g

Your max_length is set to 80, but your input_length is only 42. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=21)
Your max_length is set to 100, but your input_length is only 27. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[829번째 진g
[830번째 진g
[831번째 진g
[832번째 진g
[833번째 진g
[834번째 진g
[835번째 진g
[836번째 진g
[837번째 진g
[838번째 진g

Your max_length is set to 100, but your input_length is only 24. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[839번째 진g

Your max_length is set to 100, but your input_length is only 21. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=10)

[840번째 진g
[841번째 진g
[842번째 진g
[843번째 진g
[844번째 진g
[845번째 진g
[846번째 진g
[847번째 진g
[848번째 진g
[849번째 진g
[850번째 진g
[851번째 진g
[852번째 진g
[853번째 진g
[854번째 진g
[855번째 진g
[856번째 진g
[857번째 진g
[858번째 진g
[859번째 진g

Your max_length is set to 100, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)

[860번째 진g
[861번째 진g
[862번째 진g
[863번째 진g
[864번째 진g
[865번째 진g
[866번째 진g
[867번째 진g
[868번째 진g
[869번째 진g
[870번째 진g
[871번째 진g

Your max_length is set to 80, but your input_length is only 14. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=7)

[872번째 진g
[873번째 진g
[874번째 진g
[875번째 진g
[876번째 진g
[877번째 진g
[878번째 진g
[879번째 진g
[880번째 진g

Your max_length is set to 80, but your input_length is only 5. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=2)

[881번째 진g
[882번째 진g
[883번째 진g
[884번째 진g
[885번째 진g
[886번째 진g
[887번째 진g
[888번째 진g
[889번째 진g
[890번째 진g
[891번째 진g
[892번째 진g
[893번째 진g
[894번째 진g

Your max_length is set to 80, but your input_length is only 59. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=29)

[895번째 진g
[896번째 진g
[897번째 진g
[898번째 진g
[899번째 진g
[900번째 진g

Your max_length is set to 80, but your input_length is only 17. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=8)

[901번째 진g

Your max_length is set to 80, but your input_length is only 35. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=17)

[902번째 진g
[903번째 진g
[904번째 진g
[905번째 진g
[906번째 진g
[907번째 진g
[908번째 진g
[909번째 진g
[910번째 진g
[911번째 진g
[912번째 진g
[913번째 진g

Your max_length is set to 100, but your input_length is only 26. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=13)

[914번째 진g
[915번째 진g

Your max_length is set to 100, but your input_length is only 23. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=11)

[916번째 진g
[917번째 진g
[918번째 진g
[919번째 진g
[920번째 진g
[921번째 진g
[922번째 진g
[923번째 진g
[924번째 진g
[925번째 진g
[926번째 진g
[927번째 진g
[928번째 진g
[929번째 진g
[930번째 진g
[931번째 진g
[932번째 진g
[933번째 진g
[934번째 진g
[935번째 진g
[936번째 진g

Your max_length is set to 100, but your input_length is only 34. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=17)

[937번째 진g
[938번째 진g
[939번째 진g
[940번째 진g
[941번째 진g
[942번째 진g
[943번째 진g
[944번째 진g
[945번째 진g
[946번째 진g
[947번째 진g
[948번째 진g
[949번째 진g
[950번째 진g
[951번째 진g
[952번째 진g
[953번째 진g
[954번째 진g
[955번째 진g
[956번째 진g
[957번째 진g
[958번째 진g
[959번째 진g
[960번째 진g
[961번째 진g
[962번째 진g
[963번째 진g
[964번째 진g
[965번째 진g
[966번째 진g
[967번째 진g
[968번째 진g
[969번째 진g
[970번째 진g

Your max_length is set to 100, but your input_length is only 31. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=15)

[971번째 진g
[972번째 진g
[973번째 진g
[974번째 진g
[975번째 진g
[976번째 진g
[977번째 진g
[978번째 진g
[979번째 진g
[980번째 진g
[981번째 진g
[982번째 진g
[983번째 진g
[984번째 진g
[985번째 진g
[986번째 진g
[987번째 진g
[988번째 진g
[989번째 진g
[990번째 진g
[991번째 진g
[992번째 진g
[993번째 진g
[994번째 진g
[995번째 진g

Your max_length is set to 100, but your input_length is only 28. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=14)

[996번째 진g
[997번째 진g
[998번째 진g
[999번째 진g

# 중립 제거 이거 안쓸듯

In [7]:
df = df[df["제목"] != "뉴스 없음"]
df

,회사,제목,URL,본문,날짜,티커,당일종가,다음날종가,상승여부,요약
0,AMT,How to Find Strong Finance Stocks Slated for P...,https://finance.yahoo.com/news/strong-finance-...,Quarterly financial reports play a vital role ...,2024-07-17 22:00,AMT,208.006180,205.595444,0.0,"The Zacks Earnings ESP, or Expected Surprise P..."
1,APO,Mastering Media Outreach: Strategies for Build...,https://finance.yahoo.com/news/mastering-media...,"NEW YORK, March 19, 2025 (GLOBE NEWSWIRE) --\n...",2025-03-19 22:00,APO,142.892090,144.257248,1.0,Nearly three out of four journalists say most ...
2,BRK-B,Warren Buffett’s best and worst investments in...,https://finance.yahoo.com/news/warren-buffett-...,"OMAHA, Neb. (AP) — Billionaire investorWarren ...",2025-05-04 06:01,BRK-B,539.799988,512.150024,0.0,"Buffett, one of theworld's richest peopleand m..."
3,COF,Cap One-Discover deal detractors assail report...,https://finance.yahoo.com/news/cap-one-discove...,This story was originally published onPayments...,2025-04-07 00:35,COF,150.090897,154.177841,1.0,The Justice Department will allow the $35 bill...
4,ANSS,Reflecting On Vertical Software Stocks’ Q3 Ear...,https://finance.yahoo.com/news/reflecting-vert...,The end of an earnings season can be a great t...,2025-01-17 18:04,ANSS,349.929993,352.070007,1.0,The 15 vertical software stocks we track repor...
...,...,...,...,...,...,...,...,...,...,...
995,HSY,"Mind-Blowingly Fruity, Shockingly Crunchy: Jol...",https://finance.yahoo.com/news/mind-blowingly-...,Your taste buds won't know what hit 'em\nHERSH...,2025-03-12 22:05,HSY,169.509323,170.500946,1.0,Jolly RancherFreeze Dried is a bold twist on t...
996,GOOGL,Amazon Launches Aurora DSQL: What Investors Ne...,https://finance.yahoo.com/news/amazon-launches...,AmazonAMZN-owned Amazon Web Services recently ...,2025-05-28 23:31,GOOGL,172.360001,171.860001,0.0,The Zacks Consensus Estimate for 2025 net sale...
997,APTV,"Update: Aptiv's Q2 Adjusted Earnings Rise, Rev...",https://finance.yahoo.com/news/aptiv-apos-q2-a...,"Update: Aptiv's Q2 Adjusted Earnings Rise, Rev...",2024-08-02 00:40,APTV,73.129997,69.629997,0.0,"Aptiv's Q2 Adjusted Earnings Rise, Revenue Fal..."
998,ALB,Albemarle Announces New Operating Structure to...,https://finance.yahoo.com/news/albemarle-annou...,Decision marks next step in comprehensive revi...,2024-10-07 19:45,ALB,103.478317,99.308273,0.0,Albemarle's operating structure will transitio...
999,CTAS,"The Zacks Analyst Blog Atmos Energy, Brown & B...",https://finance.yahoo.com/news/zacks-analyst-b...,"Chicago, IL – December 31, 2024 – Zacks.com an...",2024-12-31 16:15,CTAS,182.022064,181.414337,0.0,"The S&P 500 has grown an impressive 26.2%, whe..."

In [8]:
import pandas as pd
import re
import spacy
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

df1 = df.copy()
nlp = spacy.load("en_core_web_sm")

from transformers import pipeline as hf_pipeline
ner = hf_pipeline("ner", model="dslim/bert-base-NER", tokenizer="dslim/bert-base-NER", aggregation_strategy="simple")

model_name = "yiyanghkust/finbert-tone"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, trust_remote_code=True, use_safetensors=True)
sentiment = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, return_all_scores=True)

from collections import Counter

sentiment_results = []

for _, row in df1.iterrows():
    try:
        text = row["요약"]
        company_name = row["회사"]

        # 뉴스 없음 또는 요약 실패일 경우 Neutral 처리
        if not isinstance(text, str) or text.strip() == "" or "뉴스 없음" in text or "요약 실패" in text:
            sentiment_results.append("Neutral")
            continue

        # 1. 문장 분리
        split_points = [m.start() for m in re.finditer(r'\bwhile\b|\bbut\b', text)]
        clauses = []
        start = 0
        for point in split_points:
            clauses.append(text[start:point].strip())
            start = point
        clauses.append(text[start:].strip())

        # 2. 병합
        final_clauses = []
        for i, clause in enumerate(clauses):
            doc = nlp(clause)
            if i > 0 and len(doc) > 0 and doc[0].pos_ == "VERB":
                final_clauses[-1] += " " + clause
            else:
                final_clauses.append(clause)

        # 3. 감성 분석 (회사명 언급된 절 모두)
        company_sentiments = []
        for clause in final_clauses:
            ents = ner(clause)
            orgs = [e["word"] for e in ents if e["entity_group"] == "ORG"]

            if not orgs and company_name in clause:
                orgs.append(company_name)

            if any(company_name in o for o in orgs):
                preds = sentiment(clause)[0]
                top = max(preds, key=lambda x: x["score"])
                company_sentiments.append(top["label"])

        # 4. 다수결 또는 fallback
        if company_sentiments:
            final_sentiment = Counter(company_sentiments).most_common(1)[0][0]
            sentiment_results.append(final_sentiment)
        else:
            preds = sentiment(text[:512])[0]
            top = max(preds, key=lambda x: x["score"])
            sentiment_results.append(top["label"])

    except Exception as e:
        print(f"❌ 예외 발생: {e}")
        sentiment_results.append("Neutral")
df1["감성분석"] = sentiment_results

config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0

config.json:   0%|          | 0.00/533 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

Device set to use cuda:0
/usr/local/lib/python3.11/dist-packages/transformers/pipelines/text_classification.py:106: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

❌ 예외 발생: The size of tensor a (573) must match the size of tensor b (512) at non-singleton dimension 1
❌ 예외 발생: The size of tensor a (573) must match the size of tensor b (512) at non-singleton dimension 1
❌ 예외 발생: The size of tensor a (518) must match the size of tensor b (512) at non-singleton dimension 1

In [13]:
import pandas as pd
import re
import spacy
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

df1 = df.copy()
# 2. spaCy 로드
nlp = spacy.load("en_core_web_sm")

# 3. NER 파이프라인
from transformers import pipeline as hf_pipeline
ner = hf_pipeline("ner", model="dslim/bert-base-NER", tokenizer="dslim/bert-base-NER", aggregation_strategy="simple")

# 4. 감성 분석 파이프라인
model_name = "yiyanghkust/finbert-tone"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, trust_remote_code=True, use_safetensors=True)
sentiment = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, return_all_scores=True)

# 5. 결과 저장용 리스트
sentiment_results = []
for _, row in df1.iterrows():
    try:
        text = row["요약"]
        company_name = row["회사"]

        # 1. 문장 분리
        split_points = [m.start() for m in re.finditer(r'\bwhile\b|\bbut\b', text)]
        clauses = []
        start = 0
        for point in split_points:
            clauses.append(text[start:point].strip())
            start = point
        clauses.append(text[start:].strip())

        # 2. 병합
        final_clauses = []
        for i, clause in enumerate(clauses):
            doc = nlp(clause)
            if i > 0 and len(doc) > 0 and doc[0].pos_ == "VERB":
                final_clauses[-1] += " " + clause
            else:
                final_clauses.append(clause)

        found = False
        for clause in final_clauses:
            ents = ner(clause)
            orgs = [e["word"] for e in ents if e["entity_group"] == "ORG"]

            if not orgs and company_name in clause:
                orgs.append(company_name)

            if any(company_name in o for o in orgs):
                preds = sentiment(clause)[0]
                top = max(preds, key=lambda x: x["score"])
                sentiment_results.append(top["label"])
                found = True
                break

        if not found:
            preds = sentiment(text[:512])[0]
            top = max(preds, key=lambda x: x["score"])
            sentiment_results.append(top["label"])

    except Exception as e:
        print(f"❌ 예외 발생: {e}")
        sentiment_results.append("Unknown")
df1["감성분석"] = sentiment_results

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cuda:0
Device set to use cuda:0
/usr/local/lib/python3.11/dist-packages/transformers/pipelines/text_classification.py:106: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

❌ 예외 발생: The size of tensor a (573) must match the size of tensor b (512) at non-singleton dimension 1
❌ 예외 발생: The size of tensor a (573) must match the size of tensor b (512) at non-singleton dimension 1
❌ 예외 발생: The size of tensor a (518) must match the size of tensor b (512) at non-singleton dimension 1

In [17]:
df2 = df1.dropna()
df2

,회사,제목,URL,본문,날짜,티커,당일종가,다음날종가,상승여부,요약,감성분석
0,AMT,How to Find Strong Finance Stocks Slated for P...,https://finance.yahoo.com/news/strong-finance-...,Quarterly financial reports play a vital role ...,2024-07-17 22:00,AMT,208.006180,205.595444,0.0,"The Zacks Earnings ESP, or Expected Surprise P...",Neutral
1,APO,Mastering Media Outreach: Strategies for Build...,https://finance.yahoo.com/news/mastering-media...,"NEW YORK, March 19, 2025 (GLOBE NEWSWIRE) --\n...",2025-03-19 22:00,APO,142.892090,144.257248,1.0,Nearly three out of four journalists say most ...,Neutral
2,BRK-B,Warren Buffett’s best and worst investments in...,https://finance.yahoo.com/news/warren-buffett-...,"OMAHA, Neb. (AP) — Billionaire investorWarren ...",2025-05-04 06:01,BRK-B,539.799988,512.150024,0.0,"Buffett, one of theworld's richest peopleand m...",Neutral
3,COF,Cap One-Discover deal detractors assail report...,https://finance.yahoo.com/news/cap-one-discove...,This story was originally published onPayments...,2025-04-07 00:35,COF,150.090897,154.177841,1.0,The Justice Department will allow the $35 bill...,Negative
4,ANSS,Reflecting On Vertical Software Stocks’ Q3 Ear...,https://finance.yahoo.com/news/reflecting-vert...,The end of an earnings season can be a great t...,2025-01-17 18:04,ANSS,349.929993,352.070007,1.0,The 15 vertical software stocks we track repor...,Positive
...,...,...,...,...,...,...,...,...,...,...,...
995,HSY,"Mind-Blowingly Fruity, Shockingly Crunchy: Jol...",https://finance.yahoo.com/news/mind-blowingly-...,Your taste buds won't know what hit 'em\nHERSH...,2025-03-12 22:05,HSY,169.509323,170.500946,1.0,Jolly RancherFreeze Dried is a bold twist on t...,Neutral
996,GOOGL,Amazon Launches Aurora DSQL: What Investors Ne...,https://finance.yahoo.com/news/amazon-launches...,AmazonAMZN-owned Amazon Web Services recently ...,2025-05-28 23:31,GOOGL,172.360001,171.860001,0.0,The Zacks Consensus Estimate for 2025 net sale...,Negative
997,APTV,"Update: Aptiv's Q2 Adjusted Earnings Rise, Rev...",https://finance.yahoo.com/news/aptiv-apos-q2-a...,"Update: Aptiv's Q2 Adjusted Earnings Rise, Rev...",2024-08-02 00:40,APTV,73.129997,69.629997,0.0,"Aptiv's Q2 Adjusted Earnings Rise, Revenue Fal...",Positive
998,ALB,Albemarle Announces New Operating Structure to...,https://finance.yahoo.com/news/albemarle-annou...,Decision marks next step in comprehensive revi...,2024-10-07 19:45,ALB,103.478317,99.308273,0.0,Albemarle's operating structure will transitio...,Neutral
999,CTAS,"The Zacks Analyst Blog Atmos Energy, Brown & B...",https://finance.yahoo.com/news/zacks-analyst-b...,"Chicago, IL – December 31, 2024 – Zacks.com an...",2024-12-31 16:15,CTAS,182.022064,181.414337,0.0,"The S&P 500 has grown an impressive 26.2%, whe...",Positive

In [25]:
df2.iloc[970]['요약']

'The S&P 500 has grown an impressive 26.2%, whereas the Dow Jones Industrial Average has climbed 14.1%. As we turn the corner into 2025, this heightened uncertainty underscores the importance of resilience in the portfolio strategy. For income-focused investors, dividend aristocrats are undeniable cornerstones for building a reliable portfolio. CTAS’s payout ratio is 38, with a five-year dividend growth rate of 21.2%. The Zacks Consensus Estimate for its fiscal 2025 earnings has increased 1.9% over the past 30 days. Shares of the Zacks Rank #2 company have gained 21.7% in 2024.'

In [18]:
df2.isnull().sum()

회사       0
제목       0
URL      0
본문       0
날짜       0
티커       0
당일종가     0
다음날종가    0
상승여부     0
요약       0
감성분석     0
dtype: int64

In [20]:
# 조건에 맞는 경우의 수 계산

predict_positive = df2[df2["감성분석"] == "Positive"].shape[0]
real_positive = df2[df2["상승여부"] == 1.0].shape[0]
# 전체 정확도 계산

positive_accuracy = real_positive / predict_positive
print(f"✅ 총 상승 일치: {real_positive} / {predict_positive} (정확도: {positive_accuracy:.2%})")

✅ 총 상승 일치: 483 / 503 (정확도: 96.02%)