In [1]:
# 매번 실행되도록 상단에 위치
!pip install numpy==1.23.5 --force-reinstall
!pip install pandas_ta
!pip install optuna

Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.23.5 which is incompatible.
albumentations 2.0.7 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
imbalanced-learn 0.13.0 requires numpy<3,>=1.24.3, but you have numpy 1.23.5 which is incompatible.
db-dtypes 1.4.3 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
albucore 0.0.24 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.23.5 which is incompatible.
blosc2 3.3.3 requires numpy>=1.26, but you have numpy 1.23.5 which is incompatible.
bigframes 2.4.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
pymc 5.22.0 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.23.5 which is incompatible.
xarray 2025.3.1 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
chex 0.1.89 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
Successfully installed numpy-1.23.5

Collecting pandas_ta
  Using cached pandas_ta-0.3.14b.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pandas_ta) (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pandas_ta) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pandas_ta) (1.17.0)
Building wheels for collected packages: pandas_ta
  Building wheel for pandas_ta (setup.py) ... done
  Created wheel for pandas_ta: filename=pandas_ta-0.3.14b0-py3-none-any.whl size=218910 sha256=7c0885f3baa3452d97f6afd827b465ab9aab50f8443a352d4bb5905760208ff7
  Stored in directory: /root/.cache/pip/wheels/7f/33/8b/50b245c5c65433cd8f5cb24ac15d97e5a3db2d41a8b6ae957d
Successfully built pandas_ta
Installing collected packages: pandas_ta
Successfully installed pandas_ta-0.3.14b0
Collecting optuna
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.13.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.2)
Downloading optuna-4.3.0-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.6/386.6 kB 11.5 MB/s eta 0:00:00
Downloading alembic-1.16.1-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 26.3 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.16.1 colorlog-6.9.0 optuna-4.3.0

In [1]:
import pandas as pd
import json

# 웹에서 S&P 500 데이터 가져오기
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
tables = pd.read_html(url)
df = tables[0]

# 티커 및 이름 정리
ticker_Group = [t.replace(".", "-") for t in df['Symbol']]
company_names = [n.replace(".", "-") for n in df['Security']]
ticker_names = dict(zip(ticker_Group, company_names))

# 티커 리스트 저장
with open("ticker_Group.txt", "w") as f:
    for t in ticker_Group:
        f.write(f"{t}\n")

# 티커-이름 딕셔너리 저장 (json)
with open("ticker_names.json", "w") as f:
    json.dump(ticker_names, f, indent=2, ensure_ascii=False)

In [2]:
import pandas as pd

# 위키피디아의 S&P 500 구성 종목 목록 URL
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

# HTML 테이블을 읽어오기
tables = pd.read_html(url)
df = tables[0]  # 첫 번째 테이블이 S&P 500 구성 종목 목록


# 티커와 기업명 추출
ticker_Group= df['Symbol'].tolist()
company_names = df['Security'].tolist()

ticker_Group = [t.replace(".", "-") for t in ticker_Group]
company_names = [t.replace(".", "-") for t in company_names]
ticker_names = dict(zip(ticker_Group, company_names))

ticker_Group
ticker_names

{'MMM': '3M',
 'AOS': 'A- O- Smith',
 'ABT': 'Abbott Laboratories',
 'ABBV': 'AbbVie',
 'ACN': 'Accenture',
 'ADBE': 'Adobe Inc-',
 'AMD': 'Advanced Micro Devices',
 'AES': 'AES Corporation',
 'AFL': 'Aflac',
 'A': 'Agilent Technologies',
 'APD': 'Air Products',
 'ABNB': 'Airbnb',
 'AKAM': 'Akamai Technologies',
 'ALB': 'Albemarle Corporation',
 'ARE': 'Alexandria Real Estate Equities',
 'ALGN': 'Align Technology',
 'ALLE': 'Allegion',
 'LNT': 'Alliant Energy',
 'ALL': 'Allstate',
 'GOOGL': 'Alphabet Inc- (Class A)',
 'GOOG': 'Alphabet Inc- (Class C)',
 'MO': 'Altria',
 'AMZN': 'Amazon',
 'AMCR': 'Amcor',
 'AEE': 'Ameren',
 'AEP': 'American Electric Power',
 'AXP': 'American Express',
 'AIG': 'American International Group',
 'AMT': 'American Tower',
 'AWK': 'American Water Works',
 'AMP': 'Ameriprise Financial',
 'AME': 'Ametek',
 'AMGN': 'Amgen',
 'APH': 'Amphenol',
 'ADI': 'Analog Devices',
 'ANSS': 'Ansys',
 'AON': 'Aon plc',
 'APA': 'APA Corporation',
 'APO': 'Apollo Global Management',
 'AAPL': 'Apple Inc-',
 'AMAT': 'Applied Materials',
 'APTV': 'Aptiv',
 'ACGL': 'Arch Capital Group',
 'ADM': 'Archer Daniels Midland',
 'ANET': 'Arista Networks',
 'AJG': 'Arthur J- Gallagher & Co-',
 'AIZ': 'Assurant',
 'T': 'AT&T',
 'ATO': 'Atmos Energy',
 'ADSK': 'Autodesk',
 'ADP': 'Automatic Data Processing',
 'AZO': 'AutoZone',
 'AVB': 'AvalonBay Communities',
 'AVY': 'Avery Dennison',
 'AXON': 'Axon Enterprise',
 'BKR': 'Baker Hughes',
 'BALL': 'Ball Corporation',
 'BAC': 'Bank of America',
 'BAX': 'Baxter International',
 'BDX': 'Becton Dickinson',
 'BRK-B': 'Berkshire Hathaway',
 'BBY': 'Best Buy',
 'TECH': 'Bio-Techne',
 'BIIB': 'Biogen',
 'BLK': 'BlackRock',
 'BX': 'Blackstone Inc-',
 'BK': 'BNY Mellon',
 'BA': 'Boeing',
 'BKNG': 'Booking Holdings',
 'BSX': 'Boston Scientific',
 'BMY': 'Bristol Myers Squibb',
 'AVGO': 'Broadcom',
 'BR': 'Broadridge Financial Solutions',
 'BRO': 'Brown & Brown',
 'BF-B': 'Brown–Forman',
 'BLDR': 'Builders FirstSource',
 'BG': 'Bunge Global',
 'BXP': 'BXP, Inc-',
 'CHRW': 'C-H- Robinson',
 'CDNS': 'Cadence Design Systems',
 'CZR': 'Caesars Entertainment',
 'CPT': 'Camden Property Trust',
 'CPB': "Campbell's Company (The)",
 'COF': 'Capital One',
 'CAH': 'Cardinal Health',
 'KMX': 'CarMax',
 'CCL': 'Carnival',
 'CARR': 'Carrier Global',
 'CAT': 'Caterpillar Inc-',
 'CBOE': 'Cboe Global Markets',
 'CBRE': 'CBRE Group',
 'CDW': 'CDW Corporation',
 'COR': 'Cencora',
 'CNC': 'Centene Corporation',
 'CNP': 'CenterPoint Energy',
 'CF': 'CF Industries',
 'CRL': 'Charles River Laboratories',
 'SCHW': 'Charles Schwab Corporation',
 'CHTR': 'Charter Communications',
 'CVX': 'Chevron Corporation',
 'CMG': 'Chipotle Mexican Grill',
 'CB': 'Chubb Limited',
 'CHD': 'Church & Dwight',
 'CI': 'Cigna',
 'CINF': 'Cincinnati Financial',
 'CTAS': 'Cintas',
 'CSCO': 'Cisco',
 'C': 'Citigroup',
 'CFG': 'Citizens Financial Group',
 'CLX': 'Clorox',
 'CME': 'CME Group',
 'CMS': 'CMS Energy',
 'KO': 'Coca-Cola Company (The)',
 'CTSH': 'Cognizant',
 'COIN': 'Coinbase',
 'CL': 'Colgate-Palmolive',
 'CMCSA': 'Comcast',
 'CAG': 'Conagra Brands',
 'COP': 'ConocoPhillips',
 'ED': 'Consolidated Edison',
 'STZ': 'Constellation Brands',
 'CEG': 'Constellation Energy',
 'COO': 'Cooper Companies (The)',
 'CPRT': 'Copart',
 'GLW': 'Corning Inc-',
 'CPAY': 'Corpay',
 'CTVA': 'Corteva',
 'CSGP': 'CoStar Group',
 'COST': 'Costco',
 'CTRA': 'Coterra',
 'CRWD': 'CrowdStrike',
 'CCI': 'Crown Castle',
 'CSX': 'CSX Corporation',
 'CMI': 'Cummins',
 'CVS': 'CVS Health',
 'DHR': 'Danaher Corporation',
 'DRI': 'Darden Restaurants',
 'DVA': 'DaVita',
 'DAY': 'Dayforce',
 'DECK': 'Deckers Brands',
 'DE': 'Deere & Company',
 'DELL': 'Dell Technologies',
 'DAL': 'Delta Air Lines',
 'DVN': 'Devon Energy',
 'DXCM': 'Dexcom',
 'FANG': 'Diamondback Energy',
 'DLR': 'Digital Realty',
 'DG': 'Dollar General',
 'DLTR': 'Dollar Tree',
 'D': 'Dominion Energy',
 'DPZ': "Domino's",
 'DASH': 'DoorDash',
 'DOV': 'Dover Corporation',
 'DOW': 'Dow Inc-',
 'DHI': 'D- R- Horton',
 'DTE': 'DTE Energy',
 'DUK': 'Duke Energy',
 'DD': 'DuPont',
 'EMN': 'Eastman Chemical Company',
 'ETN': 'Eaton Corporation',
 'EBAY': 'eBay Inc-',
 'ECL': 'Ecolab',
 'EIX': 'Edison International',
 'EW': 'Edwards Lifesciences',
 'EA': 'Electronic Arts',
 'ELV': 'Elevance Health',
 'EMR': 'Emerson Electric',
 'ENPH': 'Enphase Energy',
 'ETR': 'Entergy',
 'EOG': 'EOG Resources',
 'EPAM': 'EPAM Systems',
 'EQT': 'EQT Corporation',
 'EFX': 'Equifax',
 'EQIX': 'Equinix',
 'EQR': 'Equity Residential',
 'ERIE': 'Erie Indemnity',
 'ESS': 'Essex Property Trust',
 'EL': 'Estée Lauder Companies (The)',
 'EG': 'Everest Group',
 'EVRG': 'Evergy',
 'ES': 'Eversource Energy',
 'EXC': 'Exelon',
 'EXE': 'Expand Energy',
 'EXPE': 'Expedia Group',
 'EXPD': 'Expeditors International',
 'EXR': 'Extra Space Storage',
 'XOM': 'ExxonMobil',
 'FFIV': 'F5, Inc-',
 'FDS': 'FactSet',
 'FICO': 'Fair Isaac',
 'FAST': 'Fastenal',
 'FRT': 'Federal Realty Investment Trust',
 'FDX': 'FedEx',
 'FIS': 'Fidelity National Information Services',
 'FITB': 'Fifth Third Bancorp',
 'FSLR': 'First Solar',
 'FE': 'FirstEnergy',
 'FI': 'Fiserv',
 'F': 'Ford Motor Company',
 'FTNT': 'Fortinet',
 'FTV': 'Fortive',
 'FOXA': 'Fox Corporation (Class A)',
 'FOX': 'Fox Corporation (Class B)',
 'BEN': 'Franklin Resources',
 'FCX': 'Freeport-McMoRan',
 'GRMN': 'Garmin',
 'IT': 'Gartner',
 'GE': 'GE Aerospace',
 'GEHC': 'GE HealthCare',
 'GEV': 'GE Vernova',
 'GEN': 'Gen Digital',
 'GNRC': 'Generac',
 'GD': 'General Dynamics',
 'GIS': 'General Mills',
 'GM': 'General Motors',
 'GPC': 'Genuine Parts Company',
 'GILD': 'Gilead Sciences',
 'GPN': 'Global Payments',
 'GL': 'Globe Life',
 'GDDY': 'GoDaddy',
 'GS': 'Goldman Sachs',
 'HAL': 'Halliburton',
 'HIG': 'Hartford (The)',
 'HAS': 'Hasbro',
 'HCA': 'HCA Healthcare',
 'DOC': 'Healthpeak Properties',
 'HSIC': 'Henry Schein',
 'HSY': 'Hershey Company (The)',
 'HES': 'Hess Corporation',
 'HPE': 'Hewlett Packard Enterprise',
 'HLT': 'Hilton Worldwide',
 'HOLX': 'Hologic',
 'HD': 'Home Depot (The)',
 'HON': 'Honeywell',
 'HRL': 'Hormel Foods',
 'HST': 'Host Hotels & Resorts',
 'HWM': 'Howmet Aerospace',
 'HPQ': 'HP Inc-',
 'HUBB': 'Hubbell Incorporated',
 'HUM': 'Humana',
 'HBAN': 'Huntington Bancshares',
 'HII': 'Huntington Ingalls Industries',
 'IBM': 'IBM',
 'IEX': 'IDEX Corporation',
 'IDXX': 'Idexx Laboratories',
 'ITW': 'Illinois Tool Works',
 'INCY': 'Incyte',
 'IR': 'Ingersoll Rand',
 'PODD': 'Insulet Corporation',
 'INTC': 'Intel',
 'ICE': 'Intercontinental Exchange',
 'IFF': 'International Flavors & Fragrances',
 'IP': 'International Paper',
 'IPG': 'Interpublic Group of Companies (The)',
 'INTU': 'Intuit',
 'ISRG': 'Intuitive Surgical',
 'IVZ': 'Invesco',
 'INVH': 'Invitation Homes',
 'IQV': 'IQVIA',
 'IRM': 'Iron Mountain',
 'JBHT': 'J-B- Hunt',
 'JBL': 'Jabil',
 'JKHY': 'Jack Henry & Associates',
 'J': 'Jacobs Solutions',
 'JNJ': 'Johnson & Johnson',
 'JCI': 'Johnson Controls',
 'JPM': 'JPMorgan Chase',
 'JNPR': 'Juniper Networks',
 'K': 'Kellanova',
 'KVUE': 'Kenvue',
 'KDP': 'Keurig Dr Pepper',
 'KEY': 'KeyCorp',
 'KEYS': 'Keysight Technologies',
 'KMB': 'Kimberly-Clark',
 'KIM': 'Kimco Realty',
 'KMI': 'Kinder Morgan',
 'KKR': 'KKR & Co-',
 'KLAC': 'KLA Corporation',
 'KHC': 'Kraft Heinz',
 'KR': 'Kroger',
 'LHX': 'L3Harris',
 'LH': 'Labcorp',
 'LRCX': 'Lam Research',
 'LW': 'Lamb Weston',
 'LVS': 'Las Vegas Sands',
 'LDOS': 'Leidos',
 'LEN': 'Lennar',
 'LII': 'Lennox International',
 'LLY': 'Lilly (Eli)',
 'LIN': 'Linde plc',
 'LYV': 'Live Nation Entertainment',
 'LKQ': 'LKQ Corporation',
 'LMT': 'Lockheed Martin',
 'L': 'Loews Corporation',
 'LOW': "Lowe's",
 'LULU': 'Lululemon Athletica',
 'LYB': 'LyondellBasell',
 'MTB': 'M&T Bank',
 'MPC': 'Marathon Petroleum',
 'MKTX': 'MarketAxess',
 'MAR': 'Marriott International',
 'MMC': 'Marsh McLennan',
 'MLM': 'Martin Marietta Materials',
 'MAS': 'Masco',
 'MA': 'Mastercard',
 'MTCH': 'Match Group',
 'MKC': 'McCormick & Company',
 'MCD': "McDonald's",
 'MCK': 'McKesson Corporation',
 'MDT': 'Medtronic',
 'MRK': 'Merck & Co-',
 'META': 'Meta Platforms',
 'MET': 'MetLife',
 'MTD': 'Mettler Toledo',
 'MGM': 'MGM Resorts',
 'MCHP': 'Microchip Technology',
 'MU': 'Micron Technology',
 'MSFT': 'Microsoft',
 'MAA': 'Mid-America Apartment Communities',
 'MRNA': 'Moderna',
 'MHK': 'Mohawk Industries',
 'MOH': 'Molina Healthcare',
 'TAP': 'Molson Coors Beverage Company',
 'MDLZ': 'Mondelez International',
 'MPWR': 'Monolithic Power Systems',
 'MNST': 'Monster Beverage',
 'MCO': "Moody's Corporation",
 'MS': 'Morgan Stanley',
 'MOS': 'Mosaic Company (The)',
 'MSI': 'Motorola Solutions',
 'MSCI': 'MSCI Inc-',
 'NDAQ': 'Nasdaq, Inc-',
 'NTAP': 'NetApp',
 'NFLX': 'Netflix',
 'NEM': 'Newmont',
 'NWSA': 'News Corp (Class A)',
 'NWS': 'News Corp (Class B)',
 'NEE': 'NextEra Energy',
 'NKE': 'Nike, Inc-',
 'NI': 'NiSource',
 'NDSN': 'Nordson Corporation',
 'NSC': 'Norfolk Southern',
 'NTRS': 'Northern Trust',
 'NOC': 'Northrop Grumman',
 'NCLH': 'Norwegian Cruise Line Holdings',
 'NRG': 'NRG Energy',
 'NUE': 'Nucor',
 'NVDA': 'Nvidia',
 'NVR': 'NVR, Inc-',
 'NXPI': 'NXP Semiconductors',
 'ORLY': 'O’Reilly Automotive',
 'OXY': 'Occidental Petroleum',
 'ODFL': 'Old Dominion',
 'OMC': 'Omnicom Group',
 'ON': 'ON Semiconductor',
 'OKE': 'Oneok',
 'ORCL': 'Oracle Corporation',
 'OTIS': 'Otis Worldwide',
 'PCAR': 'Paccar',
 'PKG': 'Packaging Corporation of America',
 'PLTR': 'Palantir Technologies',
 'PANW': 'Palo Alto Networks',
 'PARA': 'Paramount Global',
 'PH': 'Parker Hannifin',
 'PAYX': 'Paychex',
 'PAYC': 'Paycom',
 'PYPL': 'PayPal',
 'PNR': 'Pentair',
 'PEP': 'PepsiCo',
 'PFE': 'Pfizer',
 'PCG': 'PG&E Corporation',
 'PM': 'Philip Morris International',
 'PSX': 'Phillips 66',
 'PNW': 'Pinnacle West Capital',
 'PNC': 'PNC Financial Services',
 'POOL': 'Pool Corporation',
 'PPG': 'PPG Industries',
 'PPL': 'PPL Corporation',
 'PFG': 'Principal Financial Group',
 'PG': 'Procter & Gamble',
 'PGR': 'Progressive Corporation',
 'PLD': 'Prologis',
 'PRU': 'Prudential Financial',
 'PEG': 'Public Service Enterprise Group',
 'PTC': 'PTC Inc-',
 'PSA': 'Public Storage',
 'PHM': 'PulteGroup',
 'PWR': 'Quanta Services',
 'QCOM': 'Qualcomm',
 'DGX': 'Quest Diagnostics',
 'RL': 'Ralph Lauren Corporation',
 'RJF': 'Raymond James Financial',
 'RTX': 'RTX Corporation',
 'O': 'Realty Income',
 'REG': 'Regency Centers',
 'REGN': 'Regeneron Pharmaceuticals',
 'RF': 'Regions Financial Corporation',
 'RSG': 'Republic Services',
 'RMD': 'ResMed',
 'RVTY': 'Revvity',
 'ROK': 'Rockwell Automation',
 'ROL': 'Rollins, Inc-',
 'ROP': 'Roper Technologies',
 'ROST': 'Ross Stores',
 'RCL': 'Royal Caribbean Group',
 'SPGI': 'S&P Global',
 'CRM': 'Salesforce',
 'SBAC': 'SBA Communications',
 'SLB': 'Schlumberger',
 'STX': 'Seagate Technology',
 'SRE': 'Sempra',
 'NOW': 'ServiceNow',
 'SHW': 'Sherwin-Williams',
 'SPG': 'Simon Property Group',
 'SWKS': 'Skyworks Solutions',
 'SJM': 'J-M- Smucker Company (The)',
 'SW': 'Smurfit Westrock',
 'SNA': 'Snap-on',
 'SOLV': 'Solventum',
 'SO': 'Southern Company',
 'LUV': 'Southwest Airlines',
 'SWK': 'Stanley Black & Decker',
 'SBUX': 'Starbucks',
 'STT': 'State Street Corporation',
 'STLD': 'Steel Dynamics',
 'STE': 'Steris',
 'SYK': 'Stryker Corporation',
 'SMCI': 'Supermicro',
 'SYF': 'Synchrony Financial',
 'SNPS': 'Synopsys',
 'SYY': 'Sysco',
 'TMUS': 'T-Mobile US',
 'TROW': 'T- Rowe Price',
 'TTWO': 'Take-Two Interactive',
 'TPR': 'Tapestry, Inc-',
 'TRGP': 'Targa Resources',
 'TGT': 'Target Corporation',
 'TEL': 'TE Connectivity',
 'TDY': 'Teledyne Technologies',
 'TER': 'Teradyne',
 'TSLA': 'Tesla, Inc-',
 'TXN': 'Texas Instruments',
 'TPL': 'Texas Pacific Land Corporation',
 'TXT': 'Textron',
 'TMO': 'Thermo Fisher Scientific',
 'TJX': 'TJX Companies',
 'TKO': 'TKO Group Holdings',
 'TSCO': 'Tractor Supply',
 'TT': 'Trane Technologies',
 'TDG': 'TransDigm Group',
 'TRV': 'Travelers Companies (The)',
 'TRMB': 'Trimble Inc-',
 'TFC': 'Truist Financial',
 'TYL': 'Tyler Technologies',
 'TSN': 'Tyson Foods',
 'USB': 'U-S- Bancorp',
 'UBER': 'Uber',
 'UDR': 'UDR, Inc-',
 'ULTA': 'Ulta Beauty',
 'UNP': 'Union Pacific Corporation',
 'UAL': 'United Airlines Holdings',
 'UPS': 'United Parcel Service',
 'URI': 'United Rentals',
 'UNH': 'UnitedHealth Group',
 'UHS': 'Universal Health Services',
 'VLO': 'Valero Energy',
 'VTR': 'Ventas',
 'VLTO': 'Veralto',
 'VRSN': 'Verisign',
 'VRSK': 'Verisk Analytics',
 'VZ': 'Verizon',
 'VRTX': 'Vertex Pharmaceuticals',
 'VTRS': 'Viatris',
 'VICI': 'Vici Properties',
 'V': 'Visa Inc-',
 'VST': 'Vistra Corp-',
 'VMC': 'Vulcan Materials Company',
 'WRB': 'W- R- Berkley Corporation',
 'GWW': 'W- W- Grainger',
 'WAB': 'Wabtec',
 'WBA': 'Walgreens Boots Alliance',
 'WMT': 'Walmart',
 'DIS': 'Walt Disney Company (The)',
 'WBD': 'Warner Bros- Discovery',
 'WM': 'Waste Management',
 'WAT': 'Waters Corporation',
 'WEC': 'WEC Energy Group',
 'WFC': 'Wells Fargo',
 'WELL': 'Welltower',
 'WST': 'West Pharmaceutical Services',
 'WDC': 'Western Digital',
 'WY': 'Weyerhaeuser',
 'WSM': 'Williams-Sonoma, Inc-',
 'WMB': 'Williams Companies',
 'WTW': 'Willis Towers Watson',
 'WDAY': 'Workday, Inc-',
 'WYNN': 'Wynn Resorts',
 'XEL': 'Xcel Energy',
 'XYL': 'Xylem Inc-',
 'YUM': 'Yum! Brands',
 'ZBRA': 'Zebra Technologies',
 'ZBH': 'Zimmer Biomet',
 'ZTS': 'Zoetis'}

주식 정보 모으기

In [3]:
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
NaN = np.nan
def get_value_safe(df, column_names):
    for col in column_names:
        if col in df.columns:
            series = df[col].dropna()
            if not series.empty:
                return series.iloc[0]
    return np.nan

def get_valuation_ratios_for_date(ticker_obj, info, fin, bal, shares, date):
    fin_q = fin.loc[fin.index <= date]
    bal_q = bal.loc[bal.index <= date]

    try:
        if fin_q.empty or bal_q.empty:
            raise ValueError("📉 재무제표 없음")

        # ✅ 가장 최근 분기 1개만 사용
        recent_fin = fin_q.iloc[-1]
        recent_bal = bal_q.iloc[-1]

        net_income = recent_fin.get("Net Income", np.nan)
        revenue = recent_fin.get("Total Revenue", np.nan)

        equity = get_value_safe(pd.DataFrame([recent_bal]), [
            'Total Equity Gross Minority Interest', 'Total Stockholder Equity'])
        liabilities = get_value_safe(pd.DataFrame([recent_bal]), [
            'Total Liabilities Net Minority Interest', 'Total Liabilities'])
        current_assets = get_value_safe(pd.DataFrame([recent_bal]), ['Total Current Assets'])
        current_liabilities = get_value_safe(pd.DataFrame([recent_bal]), ['Total Current Liabilities'])

        # 시가총액 계산
        market_cap = info['previousClose'] * shares if shares and info.get('previousClose') else np.nan

        # 지표 계산
        per = market_cap / net_income if pd.notna(market_cap) and pd.notna(net_income) and net_income != 0 else np.nan
        pbr = market_cap / equity if pd.notna(market_cap) and pd.notna(equity) and equity != 0 else np.nan
        psr = market_cap / revenue if pd.notna(market_cap) and pd.notna(revenue) and revenue != 0 else np.nan
        debt_equity = liabilities / equity if pd.notna(liabilities) and pd.notna(equity) and equity != 0 else np.nan

        # 유동비율
        if pd.notna(current_assets) and pd.notna(current_liabilities):
            current_ratio = current_assets / current_liabilities if current_liabilities != 0 else np.inf
        else:
            current_ratio = 0.01

        return {
            'PER': per,
            'PBR': pbr,
            'PSR': psr,
            'Current_Ratio': current_ratio,
            'Debt_Equity': debt_equity
        }

    except Exception as e:
        print("💥 계산 중 오류:", e)
        return {
            'PER': np.nan,
            'PBR': np.nan,
            'PSR': np.nan,
            'Current_Ratio': np.nan,
            'Debt_Equity': np.nan
        }

def check_buy_signal(ticker_symbol):
    print(f"{ticker_symbol}...")
    ticker = yf.Ticker(ticker_symbol)
    df = ticker.history(period="30mo")
    df['Ticker'] = ticker_symbol

    # 기술적 지표: 모두 shift(1)로 미래 누수 방지
    df["RSI"] = ta.rsi(df["Close"], length=5).shift(1)

    bb = ta.bbands(df["Close"], length=10, std=2.0)
    for col in bb.columns:
        df[col] = bb[col].shift(1)
    df['SMA5'] = df['Close'].rolling(window=5).mean().shift(1)
    df['SMA10'] = df['Close'].rolling(window=10).mean().shift(1)
    df['BB_Dist'] = df['Close'] - df['BBL_10_2.0']

    macd = ta.macd(df["Close"], fast=6, slow=13, signal=4)
    for col in macd.columns:
        df[col] = macd[col].shift(1)

    stoch = ta.stoch(df["High"], df["Low"], df["Close"], k=5, d=3, smooth_k=1)
    for col in stoch.columns:
        df[col] = stoch[col].shift(1)

    df["OBV"] = ta.obv(df["Close"], df["Volume"]).shift(1)
    # ATR (Average True Range) 추가: 변동성 지표
    df["ATR"] = ta.atr(df["High"], df["Low"], df["Close"], length=14).shift(1)
    df['Golden_Cross'] = (
        (df['SMA5'].shift(1) < df['SMA10'].shift(1)) &
        (df['SMA5'] >= df['SMA10'])
    ).astype(int)
    df["ADX"] = ta.adx(df["High"], df["Low"], df["Close"]).iloc[:, 0].shift(1)
    df["CCI"] = ta.cci(df["High"], df["Low"], df["Close"], length=20).shift(1)
    df["ROC"] = ta.roc(df["Close"], length=10).shift(1)
    df["CMF"] = ta.cmf(df["High"], df["Low"], df["Close"], df["Volume"], length=20).shift(1)
    df["ADL"] = ta.ad(df["High"], df["Low"], df["Close"], df["Volume"]).shift(1)



    df["Yesterday_Close"] = df["Close"].shift(1)
    df["Target"] = (df["Yesterday_Close"] <= df["Close"]).astype(int)

    df.reset_index(inplace=True)
    df['Date'] = df['Date'].dt.date

    # Drop NaNs
    df = df.dropna(subset=[
        "RSI", "BBL_10_2.0", "BBU_10_2.0", "SMA5", "SMA10",
        "MACD_6_13_4", "MACDh_6_13_4", "STOCHk_5_3_1", "STOCHd_5_3_1", "OBV","ATR"
    ])
    # 불필요한 열 제거
    df = df.drop(columns=[
      'BBL_10_2.0','BBM_10_2.0','BBU_10_2.0',
      'BBB_10_2.0','BBP_10_2.0', "SMA5", "SMA10"
    ])

    return df


all_dfs = []
for t in ticker_Group:
    df = check_buy_signal(t)
    if df is not None:
        all_dfs.append(df)

combined_df = pd.concat(all_dfs, ignore_index=True) if all_dfs else pd.DataFrame()

from datetime import datetime, time
import pytz

def is_kst_predict_time():
    now_kst = datetime.now(pytz.timezone("Asia/Seoul")).time()
    # 예측 가능한 구간: 오전 05:01 ~ 오후 22:29
    return time(5, 0) <= now_kst < time(22, 30)
today_kst = datetime.now(pytz.timezone("Asia/Seoul")).date()

if is_kst_predict_time():
    # 어제까지의 종가로 오늘 예측 가능
    combined_df = combined_df[combined_df["Date"] <= today_kst]
else:
    # 장이 아직 안 열렸거나 진행 중 → 전날까지만 사용
    combined_df = combined_df[combined_df["Date"] < today_kst]

MMM...
AOS...
ABT...
ABBV...
ACN...
ADBE...
AMD...
AES...
AFL...
A...
APD...
ABNB...
AKAM...
ALB...
ARE...
ALGN...
ALLE...
LNT...
ALL...
GOOGL...
GOOG...
MO...
AMZN...
AMCR...
AEE...
AEP...
AXP...
AIG...
AMT...
AWK...
AMP...
AME...
AMGN...
APH...
ADI...
ANSS...
AON...
APA...
APO...
AAPL...
AMAT...
APTV...
ACGL...
ADM...
ANET...
AJG...
AIZ...
T...
ATO...
ADSK...
ADP...
AZO...
AVB...
AVY...
AXON...
BKR...
BALL...
BAC...
BAX...
BDX...
BRK-B...
BBY...
TECH...
BIIB...
BLK...
BX...
BK...
BA...
BKNG...
BSX...
BMY...
AVGO...
BR...
BRO...
BF-B...
BLDR...
BG...
BXP...
CHRW...
CDNS...
CZR...
CPT...
CPB...
COF...
CAH...
KMX...
CCL...
CARR...
CAT...
CBOE...
CBRE...
CDW...
COR...
CNC...
CNP...
CF...
CRL...
SCHW...
CHTR...
CVX...
CMG...
CB...
CHD...
CI...
CINF...
CTAS...
CSCO...
C...
CFG...
CLX...
CME...
CMS...
KO...
CTSH...
COIN...
CL...
CMCSA...
CAG...
COP...
ED...
STZ...
CEG...
COO...
CPRT...
GLW...
CPAY...
CTVA...
CSGP...
COST...
CTRA...
CRWD...
CCI...
CSX...
CMI...
CVS...
DHR...
DRI...
DVA...
DAY...
DECK...
DE...
DELL...
DAL...
DVN...
DXCM...
FANG...
DLR...
DG...
DLTR...
D...
DPZ...
DASH...
DOV...
DOW...
DHI...
DTE...
DUK...
DD...
EMN...
ETN...
EBAY...
ECL...
EIX...
EW...
EA...
ELV...
EMR...
ENPH...
ETR...
EOG...
EPAM...
EQT...
EFX...
EQIX...
EQR...
ERIE...
ESS...
EL...
EG...
EVRG...
ES...
EXC...
EXE...
EXPE...
EXPD...
EXR...
XOM...
FFIV...
FDS...
FICO...
FAST...
FRT...
FDX...
FIS...
FITB...
FSLR...
FE...
FI...
F...
FTNT...
FTV...
FOXA...
FOX...
BEN...
FCX...
GRMN...
IT...
GE...
GEHC...
GEV...
GEN...
GNRC...
GD...
GIS...
GM...
GPC...
GILD...
GPN...
GL...
GDDY...
GS...
HAL...
HIG...
HAS...
HCA...
DOC...
HSIC...
HSY...
HES...
HPE...
HLT...
HOLX...
HD...
HON...
HRL...
HST...
HWM...
HPQ...
HUBB...
HUM...
HBAN...
HII...
IBM...
IEX...
IDXX...
ITW...
INCY...
IR...
PODD...
INTC...
ICE...
IFF...
IP...
IPG...
INTU...
ISRG...
IVZ...
INVH...
IQV...
IRM...
JBHT...
JBL...
JKHY...
J...
JNJ...
JCI...
JPM...
JNPR...
K...
KVUE...
KDP...
KEY...
KEYS...
KMB...
KIM...
KMI...
KKR...
KLAC...
KHC...
KR...
LHX...
LH...
LRCX...
LW...
LVS...
LDOS...
LEN...
LII...
LLY...
LIN...
LYV...
LKQ...
LMT...
L...
LOW...
LULU...
LYB...
MTB...
MPC...
MKTX...
MAR...
MMC...
MLM...
MAS...
MA...
MTCH...
MKC...
MCD...
MCK...
MDT...
MRK...
META...
MET...
MTD...
MGM...
MCHP...
MU...
MSFT...
MAA...
MRNA...
MHK...
MOH...
TAP...
MDLZ...
MPWR...
MNST...
MCO...
MS...
MOS...
MSI...
MSCI...
NDAQ...
NTAP...
NFLX...
NEM...
NWSA...
NWS...
NEE...
NKE...
NI...
NDSN...
NSC...
NTRS...
NOC...
NCLH...
NRG...
NUE...
NVDA...
NVR...
NXPI...
ORLY...
OXY...
ODFL...
OMC...
ON...
OKE...
ORCL...
OTIS...
PCAR...
PKG...
PLTR...
PANW...
PARA...
PH...
PAYX...
PAYC...
PYPL...
PNR...
PEP...
PFE...
PCG...
PM...
PSX...
PNW...
PNC...
POOL...
PPG...
PPL...
PFG...
PG...
PGR...
PLD...
PRU...
PEG...
PTC...
PSA...
PHM...
PWR...
QCOM...
DGX...
RL...
RJF...
RTX...
O...
REG...
REGN...
RF...
RSG...
RMD...
RVTY...
ROK...
ROL...
ROP...
ROST...
RCL...
SPGI...
CRM...
SBAC...
SLB...
STX...
SRE...
NOW...
SHW...
SPG...
SWKS...
SJM...
SW...
SNA...
SOLV...
SO...
LUV...
SWK...
SBUX...
STT...
STLD...
STE...
SYK...
SMCI...
SYF...
SNPS...
SYY...
TMUS...
TROW...
TTWO...
TPR...
TRGP...
TGT...
TEL...
TDY...
TER...
TSLA...
TXN...
TPL...
TXT...
TMO...
TJX...
TKO...
TSCO...
TT...
TDG...
TRV...
TRMB...
TFC...
TYL...
TSN...
USB...
UBER...
UDR...
ULTA...
UNP...
UAL...
UPS...
URI...
UNH...
UHS...
VLO...
VTR...
VLTO...
VRSN...
VRSK...
VZ...
VRTX...
VTRS...
VICI...
V...
VST...
VMC...
WRB...
GWW...
WAB...
WBA...
WMT...
DIS...
WBD...
WM...
WAT...
WEC...
WFC...
WELL...
WST...
WDC...
WY...
WSM...
WMB...
WTW...
WDAY...
WYNN...
XEL...
XYL...
YUM...
ZBRA...
ZBH...
ZTS...

In [4]:
combined_df.isnull().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Dividends             0
Stock Splits          0
Ticker                0
RSI                   0
BB_Dist               0
MACD_6_13_4           0
MACDh_6_13_4          0
MACDs_6_13_4          0
STOCHk_5_3_1          0
STOCHd_5_3_1          0
OBV                   0
ATR                   0
Golden_Cross          0
ADX                6036
CCI                2012
ROC                   0
CMF                2012
ADL                   0
Yesterday_Close       0
Target                0
dtype: int64

In [5]:
combined_df = combined_df.dropna()

In [6]:
import os
import pandas as pd
from datetime import date
from google.colab import drive
from datetime import datetime
import pytz

# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# 2. 오늘 날짜
seoul_tz = pytz.timezone("Asia/Seoul")
today = datetime.now(seoul_tz).strftime("%Y-%m-%d")
file_path = f"/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/차트데이터/({today})차트.csv"

combined_df.to_csv(file_path, index=False)
print("✅ 저장 완료:", file_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ 저장 완료: /content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/차트데이터/(2025-05-31)차트.csv

다음날 검증할때

In [7]:
from datetime import datetime, timedelta
import pytz

# 서울 기준 어제 날짜 구하기
seoul_tz = pytz.timezone("Asia/Seoul")
yesterday = (datetime.now(seoul_tz) - timedelta(days=1)).date()
# 날짜 필터링
ccd = combined_df[combined_df["Date"] == yesterday]

# 결과 저장할 리스트
results = []

# 필터링된 ccd에서 Ticker와 Target 가져와서 변환
for i, row in ccd.iterrows():
    ticker = row["Ticker"]
    prob = row["Target"]
    kor_name = ticker_names.get(ticker, ticker)  # 한국어 이름 매핑
    results.append({
        "Ticker": ticker,
        "종목": kor_name,
        "상승여부": "상승" if prob == 1 else "하락"
    })

# 결과 DataFrame 생성
df_val = pd.DataFrame(results)
df_val = df_val.iloc[:,1:4]
df_val

# 2. 오늘 날짜
seoul_tz = pytz.timezone("Asia/Seoul")
today = datetime.now(seoul_tz).strftime("%Y-%m-%d")
file_path = f"/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/검증데이터/({today})검증.csv"

df_val.to_csv(file_path, index=False)
print("✅ 저장 완료:", file_path)

✅ 저장 완료: /content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/검증데이터/(2025-05-31)검증.csv

# 데이터셋 분리

In [ ]:
data = combined_df
features = [
    'RSI', 'BB_Dist', 'MACD_6_13_4', 'MACDh_6_13_4', 'MACDs_6_13_4',
    'STOCHk_5_3_1', 'STOCHd_5_3_1', 'OBV','ATR',
    'Golden_Cross' ,'ADX', 'CCI', 'ROC', 'CMF','ADL'
]

target = 'Target'
X = data[features]
y = data[target]
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((239112, 15), (59779, 15), (239112,), (59779,))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
y_proba = clf.predict_proba(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8041451867438191

In [ ]:
import optuna
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 500, 4000),
        'max_depth': trial.suggest_int('max_depth', 8, 16),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 300),
        'gamma': trial.suggest_int('gamma', 1, 3),
        'learning_rate': 0.01,
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0, step=0.1),
        'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
        'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
        'subsample': trial.suggest_categorical('subsample', [0.6, 0.7, 0.8, 1.0]),
        'random_state': 42,
        'use_label_encoder': False,
        'eval_metric': 'mlogloss'
    }
    model = XGBClassifier(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(accuracy)
    return accuracy

study = optuna.create_study(direction='maximize')  # accuracy이므로 maximize
study.optimize(objective, n_trials=50)

print("Best trial:")
print("  Value: ", study.best_trial.value)
from xgboost import XGBClassifier
best_params = study.best_params
final_model = XGBClassifier(random_state=42, **best_params)
final_model.fit(X_train, y_train)
y_pred = final_model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy = {accuracy:.2f}')

[I 2025-05-28 08:32:20,316] A new study created in memory with name: no-name-f2683402-4cee-4900-81eb-f271592bd8c2
<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:32:20] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:32:27,837] Trial 0 finished with value: 0.7984007226859829 and parameters: {'n_estimators': 516, 'max_depth': 9, 'min_child_weight': 152, 'gamma': 2, 'colsample_bytree': 0.5, 'reg_lambda': 1.044966027856773, 'reg_alpha': 0.011018529938450561, 'subsample': 0.6}. Best is trial 0 with value: 0.7984007226859829.

0.7984007226859829

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:32:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:32:52,316] Trial 1 finished with value: 0.8310554226541981 and parameters: {'n_estimators': 3350, 'max_depth': 14, 'min_child_weight': 268, 'gamma': 3, 'colsample_bytree': 0.6, 'reg_lambda': 1.4936659000239179, 'reg_alpha': 0.04678375177948299, 'subsample': 0.6}. Best is trial 1 with value: 0.8310554226541981.

0.8310554226541981

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:32:52] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:33:18,991] Trial 2 finished with value: 0.8367766866855145 and parameters: {'n_estimators': 3292, 'max_depth': 8, 'min_child_weight': 18, 'gamma': 2, 'colsample_bytree': 0.6, 'reg_lambda': 0.009187709071911023, 'reg_alpha': 0.003389953962922714, 'subsample': 0.6}. Best is trial 2 with value: 0.8367766866855145.

0.8367766866855145

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:33:19] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:33:32,375] Trial 3 finished with value: 0.8317914917108586 and parameters: {'n_estimators': 1016, 'max_depth': 12, 'min_child_weight': 37, 'gamma': 3, 'colsample_bytree': 0.6, 'reg_lambda': 0.009164194934000027, 'reg_alpha': 0.19943238962726784, 'subsample': 0.6}. Best is trial 2 with value: 0.8367766866855145.

0.8317914917108586

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:33:32] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:33:53,520] Trial 4 finished with value: 0.834351004566974 and parameters: {'n_estimators': 2745, 'max_depth': 8, 'min_child_weight': 92, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 3.1772862751326083, 'reg_alpha': 0.011475866516134104, 'subsample': 0.6}. Best is trial 2 with value: 0.8367766866855145.

0.834351004566974

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:33:53] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:34:17,901] Trial 5 finished with value: 0.8354049216253743 and parameters: {'n_estimators': 3268, 'max_depth': 8, 'min_child_weight': 36, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 0.046894965615803676, 'reg_alpha': 1.9038122826429686, 'subsample': 1.0}. Best is trial 2 with value: 0.8367766866855145.

0.8354049216253743

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:34:18] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:34:41,197] Trial 6 finished with value: 0.8359067868912793 and parameters: {'n_estimators': 2528, 'max_depth': 13, 'min_child_weight': 113, 'gamma': 2, 'colsample_bytree': 1.0, 'reg_lambda': 0.0018540023014050726, 'reg_alpha': 0.0032743784904610963, 'subsample': 1.0}. Best is trial 2 with value: 0.8367766866855145.

0.8359067868912793

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:34:41] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:35:00,445] Trial 7 finished with value: 0.8328788664536527 and parameters: {'n_estimators': 2179, 'max_depth': 10, 'min_child_weight': 15, 'gamma': 3, 'colsample_bytree': 0.5, 'reg_lambda': 0.008646678702693115, 'reg_alpha': 3.885049497382779, 'subsample': 0.7}. Best is trial 2 with value: 0.8367766866855145.

0.8328788664536527

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:35:00] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:35:21,621] Trial 8 finished with value: 0.8322264416079763 and parameters: {'n_estimators': 2155, 'max_depth': 13, 'min_child_weight': 244, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 0.15970267509835878, 'reg_alpha': 0.9818191933800632, 'subsample': 0.7}. Best is trial 2 with value: 0.8367766866855145.

0.8322264416079763

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:35:21] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:35:28,651] Trial 9 finished with value: 0.827090687053549 and parameters: {'n_estimators': 619, 'max_depth': 14, 'min_child_weight': 86, 'gamma': 3, 'colsample_bytree': 0.9, 'reg_lambda': 1.7197236041592574, 'reg_alpha': 0.026693096467542712, 'subsample': 0.7}. Best is trial 2 with value: 0.8367766866855145.

0.827090687053549

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:35:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:36:04,977] Trial 10 finished with value: 0.8371949077404353 and parameters: {'n_estimators': 3813, 'max_depth': 16, 'min_child_weight': 195, 'gamma': 2, 'colsample_bytree': 0.7, 'reg_lambda': 0.0011760770322653074, 'reg_alpha': 0.0010691929826952315, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8371949077404353

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:36:05] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:36:38,677] Trial 11 finished with value: 0.8368937885808924 and parameters: {'n_estimators': 3844, 'max_depth': 16, 'min_child_weight': 189, 'gamma': 2, 'colsample_bytree': 0.7, 'reg_lambda': 0.0011456782847833534, 'reg_alpha': 0.0010212862920826354, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8368937885808924

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:36:38] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:37:20,902] Trial 12 finished with value: 0.8370945346872543 and parameters: {'n_estimators': 3904, 'max_depth': 16, 'min_child_weight': 199, 'gamma': 2, 'colsample_bytree': 0.7, 'reg_lambda': 0.001083525864144067, 'reg_alpha': 0.0010107708916468683, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8370945346872543

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:37:21] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:37:57,673] Trial 13 finished with value: 0.8370443481606638 and parameters: {'n_estimators': 3999, 'max_depth': 16, 'min_child_weight': 219, 'gamma': 2, 'colsample_bytree': 0.8, 'reg_lambda': 0.0028442995771981983, 'reg_alpha': 0.0012541902202327963, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8370443481606638

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:37:57] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:38:28,292] Trial 14 finished with value: 0.8340331565652341 and parameters: {'n_estimators': 3695, 'max_depth': 15, 'min_child_weight': 295, 'gamma': 2, 'colsample_bytree': 0.7, 'reg_lambda': 0.04796428419662445, 'reg_alpha': 0.4022377855558664, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8340331565652341

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:38:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:38:41,874] Trial 15 finished with value: 0.8309215919166234 and parameters: {'n_estimators': 1514, 'max_depth': 11, 'min_child_weight': 186, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 0.004792022692141806, 'reg_alpha': 0.004315692267547884, 'subsample': 0.8}. Best is trial 10 with value: 0.8371949077404353.

0.8309215919166234

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:38:42] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:39:10,585] Trial 16 finished with value: 0.8373789250046004 and parameters: {'n_estimators': 2933, 'max_depth': 15, 'min_child_weight': 159, 'gamma': 2, 'colsample_bytree': 0.7, 'reg_lambda': 0.0010169085405553947, 'reg_alpha': 0.04997259761504576, 'subsample': 0.8}. Best is trial 16 with value: 0.8373789250046004.

0.8373789250046004

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:39:10] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:39:40,168] Trial 17 finished with value: 0.8375462134265688 and parameters: {'n_estimators': 2895, 'max_depth': 15, 'min_child_weight': 150, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 0.4062381080370918, 'reg_alpha': 0.09411977022449905, 'subsample': 0.8}. Best is trial 17 with value: 0.8375462134265688.

0.8375462134265688

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:39:40] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:40:08,905] Trial 18 finished with value: 0.8376465864797498 and parameters: {'n_estimators': 2822, 'max_depth': 14, 'min_child_weight': 137, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 0.2734780753147712, 'reg_alpha': 0.08171409121735797, 'subsample': 0.8}. Best is trial 18 with value: 0.8376465864797498.

0.8376465864797498

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:40:09] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:40:28,269] Trial 19 finished with value: 0.836826873212105 and parameters: {'n_estimators': 1778, 'max_depth': 14, 'min_child_weight': 102, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 0.48953393966298037, 'reg_alpha': 0.1335923892505136, 'subsample': 0.8}. Best is trial 18 with value: 0.8376465864797498.

0.836826873212105

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:40:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:40:53,740] Trial 20 finished with value: 0.8362748214196095 and parameters: {'n_estimators': 2545, 'max_depth': 12, 'min_child_weight': 130, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 0.24197774911577236, 'reg_alpha': 9.729905279021166, 'subsample': 1.0}. Best is trial 18 with value: 0.8376465864797498.

0.8362748214196095

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:40:53] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:41:23,226] Trial 21 finished with value: 0.8376298576375529 and parameters: {'n_estimators': 2898, 'max_depth': 15, 'min_child_weight': 150, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 6.286769825653249, 'reg_alpha': 0.05374044558081347, 'subsample': 0.8}. Best is trial 18 with value: 0.8376465864797498.

0.8376298576375529

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:41:23] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:42:03,744] Trial 22 finished with value: 0.8383826555364103 and parameters: {'n_estimators': 2961, 'max_depth': 15, 'min_child_weight': 66, 'gamma': 1, 'colsample_bytree': 0.8, 'reg_lambda': 7.716136119747904, 'reg_alpha': 0.3016490635584604, 'subsample': 0.8}. Best is trial 22 with value: 0.8383826555364103.

0.8383826555364103

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:42:03] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:42:40,102] Trial 23 finished with value: 0.8383826555364103 and parameters: {'n_estimators': 3105, 'max_depth': 13, 'min_child_weight': 66, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 8.496960405057251, 'reg_alpha': 0.2995845201291017, 'subsample': 0.8}. Best is trial 22 with value: 0.8383826555364103.

0.8383826555364103

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:42:40] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:43:15,574] Trial 24 finished with value: 0.8385332151161818 and parameters: {'n_estimators': 3179, 'max_depth': 13, 'min_child_weight': 61, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 5.925721103434664, 'reg_alpha': 0.4797223521502991, 'subsample': 0.8}. Best is trial 24 with value: 0.8385332151161818.

0.8385332151161818

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:43:15] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:43:53,621] Trial 25 finished with value: 0.8383659266942135 and parameters: {'n_estimators': 3456, 'max_depth': 12, 'min_child_weight': 65, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 9.425205787863106, 'reg_alpha': 0.44227709031130186, 'subsample': 0.8}. Best is trial 24 with value: 0.8385332151161818.

0.8383659266942135

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:43:53] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:44:28,274] Trial 26 finished with value: 0.8386670458537565 and parameters: {'n_estimators': 3135, 'max_depth': 13, 'min_child_weight': 64, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 3.9835182976043884, 'reg_alpha': 0.3534934037698568, 'subsample': 0.8}. Best is trial 26 with value: 0.8386670458537565.

0.8386670458537565

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:44:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:45:06,367] Trial 27 finished with value: 0.8395369456479918 and parameters: {'n_estimators': 3640, 'max_depth': 11, 'min_child_weight': 59, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 3.8353665987062104, 'reg_alpha': 0.870460979611824, 'subsample': 0.8}. Best is trial 27 with value: 0.8395369456479918.

0.8395369456479918

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:45:06] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:46:10,661] Trial 28 finished with value: 0.8377469595329308 and parameters: {'n_estimators': 3566, 'max_depth': 11, 'min_child_weight': 2, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 3.3460978502470256, 'reg_alpha': 1.111642648009999, 'subsample': 0.7}. Best is trial 27 with value: 0.8395369456479918.

0.8377469595329308

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:46:10] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:46:37,990] Trial 29 finished with value: 0.8364922963681684 and parameters: {'n_estimators': 2465, 'max_depth': 10, 'min_child_weight': 45, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 0.8636108610418495, 'reg_alpha': 0.9325894461360377, 'subsample': 1.0}. Best is trial 27 with value: 0.8395369456479918.

0.8364922963681684

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:46:38] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:47:15,864] Trial 30 finished with value: 0.8384997574317882 and parameters: {'n_estimators': 3626, 'max_depth': 11, 'min_child_weight': 80, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 3.4334061672307192, 'reg_alpha': 4.848803851781337, 'subsample': 0.8}. Best is trial 27 with value: 0.8395369456479918.

0.8384997574317882

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:47:16] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:47:50,973] Trial 31 finished with value: 0.8388343342757247 and parameters: {'n_estimators': 3599, 'max_depth': 11, 'min_child_weight': 81, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 3.7258059889159876, 'reg_alpha': 3.4551948983352476, 'subsample': 0.8}. Best is trial 27 with value: 0.8395369456479918.

0.8388343342757247

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:47:51] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:48:18,220] Trial 32 finished with value: 0.8372450942670258 and parameters: {'n_estimators': 3240, 'max_depth': 10, 'min_child_weight': 115, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 1.299448517917142, 'reg_alpha': 2.086685112391789, 'subsample': 0.8}. Best is trial 27 with value: 0.8395369456479918.

0.8372450942670258

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:48:18] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:48:56,791] Trial 33 finished with value: 0.838416113220804 and parameters: {'n_estimators': 3173, 'max_depth': 12, 'min_child_weight': 47, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 2.2849690993079093, 'reg_alpha': 0.6925286407129613, 'subsample': 0.8}. Best is trial 27 with value: 0.8395369456479918.

0.838416113220804

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:48:56] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:49:43,448] Trial 34 finished with value: 0.8383826555364103 and parameters: {'n_estimators': 3475, 'max_depth': 13, 'min_child_weight': 29, 'gamma': 1, 'colsample_bytree': 0.9, 'reg_lambda': 5.115479871487703, 'reg_alpha': 1.955367486622698, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8383826555364103

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:49:43] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:50:20,530] Trial 35 finished with value: 0.8388510631179216 and parameters: {'n_estimators': 3398, 'max_depth': 11, 'min_child_weight': 58, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 0.8044184172207985, 'reg_alpha': 3.3154727455134, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8388510631179216

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:50:20] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:50:49,218] Trial 36 finished with value: 0.83801462100808 and parameters: {'n_estimators': 3402, 'max_depth': 9, 'min_child_weight': 85, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 0.925883039768847, 'reg_alpha': 5.065299182894227, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.83801462100808

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:50:49] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:51:35,416] Trial 37 finished with value: 0.8385666728005755 and parameters: {'n_estimators': 3670, 'max_depth': 11, 'min_child_weight': 22, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 2.2013459149473587, 'reg_alpha': 9.808193007933504, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8385666728005755

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:51:35] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:51:59,279] Trial 38 finished with value: 0.8374792980577814 and parameters: {'n_estimators': 2642, 'max_depth': 9, 'min_child_weight': 48, 'gamma': 3, 'colsample_bytree': 1.0, 'reg_lambda': 0.6654367119241791, 'reg_alpha': 3.113358445127468, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8374792980577814

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:51:59] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:52:28,177] Trial 39 finished with value: 0.8373621961624036 and parameters: {'n_estimators': 3371, 'max_depth': 10, 'min_child_weight': 110, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 0.08336782918520147, 'reg_alpha': 1.43160563058449, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8373621961624036

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:52:28] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:53:00,266] Trial 40 finished with value: 0.834836140990682 and parameters: {'n_estimators': 2323, 'max_depth': 11, 'min_child_weight': 10, 'gamma': 1, 'colsample_bytree': 0.5, 'reg_lambda': 3.6879069777165943, 'reg_alpha': 0.1809162852105051, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.834836140990682

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:53:00] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:53:43,422] Trial 41 finished with value: 0.838717232380347 and parameters: {'n_estimators': 3620, 'max_depth': 11, 'min_child_weight': 25, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 1.9260002731947512, 'reg_alpha': 9.298561056816853, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.838717232380347

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:53:43] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:54:30,528] Trial 42 finished with value: 0.8382655536410325 and parameters: {'n_estimators': 3742, 'max_depth': 12, 'min_child_weight': 30, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 1.5515826508988229, 'reg_alpha': 6.7244374819810195, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8382655536410325

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:54:30] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:55:06,963] Trial 43 finished with value: 0.8388176054335279 and parameters: {'n_estimators': 3537, 'max_depth': 11, 'min_child_weight': 74, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 2.3627234878700354, 'reg_alpha': 2.910748145405284, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8388176054335279

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:55:07] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:55:42,221] Trial 44 finished with value: 0.8382822824832293 and parameters: {'n_estimators': 3928, 'max_depth': 10, 'min_child_weight': 77, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 1.8520688645364565, 'reg_alpha': 3.1294410667753803, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8382822824832293

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:55:42] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:56:18,454] Trial 45 finished with value: 0.8373120096358131 and parameters: {'n_estimators': 3535, 'max_depth': 11, 'min_child_weight': 99, 'gamma': 2, 'colsample_bytree': 1.0, 'reg_lambda': 1.1158649899525495, 'reg_alpha': 2.708125090420055, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8373120096358131

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:56:18] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:57:00,072] Trial 46 finished with value: 0.8383491978520167 and parameters: {'n_estimators': 3774, 'max_depth': 11, 'min_child_weight': 48, 'gamma': 1, 'colsample_bytree': 1.0, 'reg_lambda': 2.627785475014233, 'reg_alpha': 6.551118944596082, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8383491978520167

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:57:00] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:57:36,454] Trial 47 finished with value: 0.8389179784867089 and parameters: {'n_estimators': 3331, 'max_depth': 12, 'min_child_weight': 36, 'gamma': 2, 'colsample_bytree': 1.0, 'reg_lambda': 0.6506099544464331, 'reg_alpha': 4.2739175778419485, 'subsample': 0.6}. Best is trial 27 with value: 0.8395369456479918.

0.8389179784867089

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:57:36] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:58:05,893] Trial 48 finished with value: 0.8385332151161818 and parameters: {'n_estimators': 3334, 'max_depth': 12, 'min_child_weight': 39, 'gamma': 3, 'colsample_bytree': 1.0, 'reg_lambda': 0.019643475955714022, 'reg_alpha': 1.4880038824521211, 'subsample': 0.7}. Best is trial 27 with value: 0.8395369456479918.

0.8385332151161818

<ipython-input-36-4a088c71a5af>:13: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-3, 10.0),
<ipython-input-36-4a088c71a5af>:14: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-3, 10.0),
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [08:58:06] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
[I 2025-05-28 08:58:30,555] Trial 49 finished with value: 0.8351874466768155 and parameters: {'n_estimators': 3980, 'max_depth': 10, 'min_child_weight': 93, 'gamma': 2, 'colsample_bytree': 0.6, 'reg_lambda': 0.5971777780055788, 'reg_alpha': 4.260284928325948, 'subsample': 1.0}. Best is trial 27 with value: 0.8395369456479918.

0.8351874466768155
Best trial:
  Value:  0.8395369456479918
Accuracy = 0.83

In [ ]:
import xgboost as xgb

model = xgb.XGBClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8213361388742767

In [ ]:
from google.colab import drive
final_model.save_model("/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/예측모델/xgb_model.json")

# 항목별 학습 그냥 해본건 무시

In [9]:
import pandas as pd
import yfinance as yf
import pandas_ta as ta
from datetime import datetime
import pytz

#오늘 날짜
today = datetime.now().date()
result_list = []

for ticker1 in ticker_Group:
    print(f"{ticker1}...")
    ticker = yf.Ticker(ticker1)
    df = ticker.history(period="2mo")
    # 기술적 지표 (단기형)
    df["RSI"] = ta.rsi(df["Close"], length=5).shift(1)
    bb = ta.bbands(df["Close"], length=10, std=2.0)
    for col in bb.columns:
        df[col] = bb[col].shift(1)
    df['SMA5'] = df['Close'].rolling(window=5).mean().shift(1)
    df['SMA10'] = df['Close'].rolling(window=10).mean().shift(1)
    df['BB_Dist'] = df['Close'] - df['BBL_10_2.0']

    macd = ta.macd(df["Close"], fast=6, slow=13, signal=4)
    for col in macd.columns:
        df[col] = macd[col].shift(1)

    stoch = ta.stoch(df["High"], df["Low"], df["Close"], k=5, d=3, smooth_k=1)
    for col in stoch.columns:
        df[col] = stoch[col].shift(1)

    df["OBV"] = ta.obv(df["Close"], df["Volume"]).shift(1)
    df["ATR"] = ta.atr(df["High"], df["Low"], df["Close"], length=14).shift(1)
    df["Golden_Cross"] = (
        (df["SMA5"].shift(1) < df["SMA10"].shift(1)) &
        (df["SMA5"] >= df["SMA10"])
    ).astype(int)
    df["ADX"] = ta.adx(df["High"], df["Low"], df["Close"]).iloc[:, 0].shift(1)
    df["CCI"] = ta.cci(df["High"], df["Low"], df["Close"], length=20).shift(1)
    df["ROC"] = ta.roc(df["Close"], length=10).shift(1)
    df["CMF"] = ta.cmf(df["High"], df["Low"], df["Close"], df["Volume"], length=20).shift(1)
    df["ADL"] = ta.ad(df["High"], df["Low"], df["Close"], df["Volume"]).shift(1)

    # 최신 행만
    last_row = df.iloc[-1]
    result_list.append({
        'Ticker': ticker1,
        'Date': today,
        'RSI': last_row['RSI'],
        'BB_Dist': last_row['BB_Dist'],
        'MACD_6_13_4': last_row['MACD_6_13_4'],
        'MACDh_6_13_4': last_row['MACDh_6_13_4'],
        'MACDs_6_13_4': last_row['MACDs_6_13_4'],
        'STOCHk_5_3_1': last_row['STOCHk_5_3_1'],
        'STOCHd_5_3_1': last_row['STOCHd_5_3_1'],
        'OBV': last_row['OBV'],
        'ATR': last_row['ATR'],
        'Golden_Cross': last_row['Golden_Cross'],
        'ADX': last_row['ADX'],
        'CCI': last_row['CCI'],
        'ROC': last_row['ROC'],
        'CMF': last_row['CMF'],
        'ADL': last_row['ADL']
    })

# 데이터프레임으로 변환
final_df = pd.DataFrame(result_list)

MMM...
AOS...
ABT...
ABBV...
ACN...
ADBE...
AMD...
AES...
AFL...
A...
APD...
ABNB...
AKAM...
ALB...
ARE...
ALGN...
ALLE...
LNT...
ALL...
GOOGL...
GOOG...
MO...
AMZN...
AMCR...
AEE...
AEP...
AXP...
AIG...
AMT...
AWK...
AMP...
AME...
AMGN...
APH...
ADI...
ANSS...
AON...
APA...
APO...
AAPL...
AMAT...
APTV...
ACGL...
ADM...
ANET...
AJG...
AIZ...
T...
ATO...
ADSK...
ADP...
AZO...
AVB...
AVY...
AXON...
BKR...
BALL...
BAC...
BAX...
BDX...
BRK-B...
BBY...
TECH...
BIIB...
BLK...
BX...
BK...
BA...
BKNG...
BSX...
BMY...
AVGO...
BR...
BRO...
BF-B...
BLDR...
BG...
BXP...
CHRW...
CDNS...
CZR...
CPT...
CPB...
COF...
CAH...
KMX...
CCL...
CARR...
CAT...
CBOE...
CBRE...
CDW...
COR...
CNC...
CNP...
CF...
CRL...
SCHW...
CHTR...
CVX...
CMG...
CB...
CHD...
CI...
CINF...
CTAS...
CSCO...
C...
CFG...
CLX...
CME...
CMS...
KO...
CTSH...
COIN...
CL...
CMCSA...
CAG...
COP...
ED...
STZ...
CEG...
COO...
CPRT...
GLW...
CPAY...
CTVA...
CSGP...
COST...
CTRA...
CRWD...
CCI...
CSX...
CMI...
CVS...
DHR...
DRI...
DVA...
DAY...
DECK...
DE...
DELL...
DAL...
DVN...
DXCM...
FANG...
DLR...
DG...
DLTR...
D...
DPZ...
DASH...
DOV...
DOW...
DHI...
DTE...
DUK...
DD...
EMN...
ETN...
EBAY...
ECL...
EIX...
EW...
EA...
ELV...
EMR...
ENPH...
ETR...
EOG...
EPAM...
EQT...
EFX...
EQIX...
EQR...
ERIE...
ESS...
EL...
EG...
EVRG...
ES...
EXC...
EXE...
EXPE...
EXPD...
EXR...
XOM...
FFIV...
FDS...
FICO...
FAST...
FRT...
FDX...
FIS...
FITB...
FSLR...
FE...
FI...
F...
FTNT...
FTV...
FOXA...
FOX...
BEN...
FCX...
GRMN...
IT...
GE...
GEHC...
GEV...
GEN...
GNRC...
GD...
GIS...
GM...
GPC...
GILD...
GPN...
GL...
GDDY...
GS...
HAL...
HIG...
HAS...
HCA...
DOC...
HSIC...
HSY...
HES...
HPE...
HLT...
HOLX...
HD...
HON...
HRL...
HST...
HWM...
HPQ...
HUBB...
HUM...
HBAN...
HII...
IBM...
IEX...
IDXX...
ITW...
INCY...
IR...
PODD...
INTC...
ICE...
IFF...
IP...
IPG...
INTU...
ISRG...
IVZ...
INVH...
IQV...
IRM...
JBHT...
JBL...
JKHY...
J...
JNJ...
JCI...
JPM...
JNPR...
K...
KVUE...
KDP...
KEY...
KEYS...
KMB...
KIM...
KMI...
KKR...
KLAC...
KHC...
KR...
LHX...
LH...
LRCX...
LW...
LVS...
LDOS...
LEN...
LII...
LLY...
LIN...
LYV...
LKQ...
LMT...
L...
LOW...
LULU...
LYB...
MTB...
MPC...
MKTX...
MAR...
MMC...
MLM...
MAS...
MA...
MTCH...
MKC...
MCD...
MCK...
MDT...
MRK...
META...
MET...
MTD...
MGM...
MCHP...
MU...
MSFT...
MAA...
MRNA...
MHK...
MOH...
TAP...
MDLZ...
MPWR...
MNST...
MCO...
MS...
MOS...
MSI...
MSCI...
NDAQ...
NTAP...
NFLX...
NEM...
NWSA...
NWS...
NEE...
NKE...
NI...
NDSN...
NSC...
NTRS...
NOC...
NCLH...
NRG...
NUE...
NVDA...
NVR...
NXPI...
ORLY...
OXY...
ODFL...
OMC...
ON...
OKE...
ORCL...
OTIS...
PCAR...
PKG...
PLTR...
PANW...
PARA...
PH...
PAYX...
PAYC...
PYPL...
PNR...
PEP...
PFE...
PCG...
PM...
PSX...
PNW...
PNC...
POOL...
PPG...
PPL...
PFG...
PG...
PGR...
PLD...
PRU...
PEG...
PTC...
PSA...
PHM...
PWR...
QCOM...
DGX...
RL...
RJF...
RTX...
O...
REG...
REGN...
RF...
RSG...
RMD...
RVTY...
ROK...
ROL...
ROP...
ROST...
RCL...
SPGI...
CRM...
SBAC...
SLB...
STX...
SRE...
NOW...
SHW...
SPG...
SWKS...
SJM...
SW...
SNA...
SOLV...
SO...
LUV...
SWK...
SBUX...
STT...
STLD...
STE...
SYK...
SMCI...
SYF...
SNPS...
SYY...
TMUS...
TROW...
TTWO...
TPR...
TRGP...
TGT...
TEL...
TDY...
TER...
TSLA...
TXN...
TPL...
TXT...
TMO...
TJX...
TKO...
TSCO...
TT...
TDG...
TRV...
TRMB...
TFC...
TYL...
TSN...
USB...
UBER...
UDR...
ULTA...
UNP...
UAL...
UPS...
URI...
UNH...
UHS...
VLO...
VTR...
VLTO...
VRSN...
VRSK...
VZ...
VRTX...
VTRS...
VICI...
V...
VST...
VMC...
WRB...
GWW...
WAB...
WBA...
WMT...
DIS...
WBD...
WM...
WAT...
WEC...
WFC...
WELL...
WST...
WDC...
WY...
WSM...
WMB...
WTW...
WDAY...
WYNN...
XEL...
XYL...
YUM...
ZBRA...
ZBH...
ZTS...

In [10]:
final_df

,Ticker,Date,RSI,BB_Dist,MACD_6_13_4,MACDh_6_13_4,MACDs_6_13_4,STOCHk_5_3_1,STOCHd_5_3_1,OBV,ATR,Golden_Cross,ADX,CCI,ROC,CMF,ADL
0,MMM,2025-05-31,55.780936,2.472205,1.150315,-0.368391,1.518706,80.270369,51.218248,22084100.0,3.536173,0.0,13.690967,50.025254,1.678952,0.197546,6.605289e+06
1,AOS,2025-05-31,30.652163,0.621529,-0.850428,-0.413019,-0.437410,22.134452,28.585425,1080400.0,1.754965,0.0,18.370174,-205.819523,-5.296262,-0.003435,2.471250e+06
2,ABT,2025-05-31,52.716509,3.165029,0.066351,-0.067468,0.133819,70.968059,47.465645,26119900.0,2.577698,0.0,10.432026,-10.278419,3.336970,0.022039,7.407707e+06
3,ABBV,2025-05-31,56.659111,5.292125,-0.287927,0.304805,-0.592732,82.615309,75.430887,6831300.0,5.105260,0.0,25.025867,-23.618985,4.610005,0.114871,4.731397e+07
4,ACN,2025-05-31,57.464454,6.224651,1.240007,-0.342550,1.582557,87.102557,63.901882,15821200.0,6.405648,0.0,20.719722,37.924095,-0.836426,0.153116,1.907535e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,XYL,2025-05-31,54.883659,2.498234,0.626078,-0.195937,0.822015,69.784561,62.153465,3644400.0,2.315901,0.0,29.634605,33.092285,0.487296,-0.133407,2.421793e+06
499,YUM,2025-05-31,37.797322,1.876150,-0.842057,-0.157424,-0.684633,48.463970,25.324285,-5773200.0,2.621695,0.0,13.629950,-118.207327,-0.284817,0.013039,9.838501e+06
500,ZBRA,2025-05-31,55.930921,6.687590,3.859900,-1.066247,4.926147,75.621569,74.961760,3212200.0,9.290817,0.0,28.270288,42.178619,-2.262168,0.198631,3.438167e+06
501,ZBH,2025-05-31,45.795558,1.639411,-1.049413,0.096377,-1.145790,70.720668,59.754338,13417800.0,2.659695,0.0,33.701003,-76.113355,-2.087491,-0.039740,2.774612e+06
502,ZTS,2025-05-31,72.201490,9.161480,2.097769,0.186595,1.911174,92.024609,87.594362,24453900.0,4.006421,0.0,9.707898,132.823016,7.887943,0.102328,1.397823e+07

In [11]:
features = [
    'RSI', 'BB_Dist', 'MACD_6_13_4', 'MACDh_6_13_4', 'MACDs_6_13_4',
    'STOCHk_5_3_1', 'STOCHd_5_3_1', 'OBV','ATR',
    'Golden_Cross','ADX', 'CCI', 'ROC', 'CMF','ADL'
]

test = final_df[features]
test

,RSI,BB_Dist,MACD_6_13_4,MACDh_6_13_4,MACDs_6_13_4,STOCHk_5_3_1,STOCHd_5_3_1,OBV,ATR,Golden_Cross,ADX,CCI,ROC,CMF,ADL
0,55.780936,2.472205,1.150315,-0.368391,1.518706,80.270369,51.218248,22084100.0,3.536173,0.0,13.690967,50.025254,1.678952,0.197546,6.605289e+06
1,30.652163,0.621529,-0.850428,-0.413019,-0.437410,22.134452,28.585425,1080400.0,1.754965,0.0,18.370174,-205.819523,-5.296262,-0.003435,2.471250e+06
2,52.716509,3.165029,0.066351,-0.067468,0.133819,70.968059,47.465645,26119900.0,2.577698,0.0,10.432026,-10.278419,3.336970,0.022039,7.407707e+06
3,56.659111,5.292125,-0.287927,0.304805,-0.592732,82.615309,75.430887,6831300.0,5.105260,0.0,25.025867,-23.618985,4.610005,0.114871,4.731397e+07
4,57.464454,6.224651,1.240007,-0.342550,1.582557,87.102557,63.901882,15821200.0,6.405648,0.0,20.719722,37.924095,-0.836426,0.153116,1.907535e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,54.883659,2.498234,0.626078,-0.195937,0.822015,69.784561,62.153465,3644400.0,2.315901,0.0,29.634605,33.092285,0.487296,-0.133407,2.421793e+06
499,37.797322,1.876150,-0.842057,-0.157424,-0.684633,48.463970,25.324285,-5773200.0,2.621695,0.0,13.629950,-118.207327,-0.284817,0.013039,9.838501e+06
500,55.930921,6.687590,3.859900,-1.066247,4.926147,75.621569,74.961760,3212200.0,9.290817,0.0,28.270288,42.178619,-2.262168,0.198631,3.438167e+06
501,45.795558,1.639411,-1.049413,0.096377,-1.145790,70.720668,59.754338,13417800.0,2.659695,0.0,33.701003,-76.113355,-2.087491,-0.039740,2.774612e+06
502,72.201490,9.161480,2.097769,0.186595,1.911174,92.024609,87.594362,24453900.0,4.006421,0.0,9.707898,132.823016,7.887943,0.102328,1.397823e+07

In [ ]:
y_pred = final_model.predict(test)
y_proba = final_model.predict_proba(test)

In [ ]:
import pandas as pd

results = []

for i, ticker in enumerate(ticker_Group):
    kor_name = ticker_names.get(ticker, ticker)
    pred = y_pred[i]
    prob = y_proba[i][1] * 100
    results.append({
        "Ticker": ticker,
        "종목": kor_name,
        "상승확률": round(prob, 2),
        "상승여부": "상승" if prob > 50 else "하락"
    })

df_result = pd.DataFrame(results)
df_result = df_result.iloc[:,1:4]
df_result

                      종목   상승확률 상승여부
0                     3M  48.14   하락
1            A- O- Smith  99.98   상승
2    Abbott Laboratories  99.85   상승
3                 AbbVie  99.24   상승
4              Accenture  94.85   상승
..                   ...    ...  ...
498           Xylem Inc-  70.47   상승
499          Yum! Brands  43.53   하락
500   Zebra Technologies  80.92   상승
501        Zimmer Biomet  93.80   상승
502               Zoetis  99.42   상승

[503 rows x 3 columns]

In [ ]:
import os
import pandas as pd
from datetime import date
from google.colab import drive
# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# 2. 오늘 날짜
today = date.today().strftime("%Y-%m-%d")
file_path = f"/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/예측데이터/({today})예측.csv"

df_result.to_csv(file_path, index=False)
print("✅ 저장 완료:", file_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ 저장 완료: /content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/예측데이터/(2025-05-27)예측.csv

In [ ]:
import os
import pandas as pd
from datetime import date
from google.colab import drive
# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

# 2. 오늘 날짜
seoul_tz = pytz.timezone("Asia/Seoul")
today = datetime.now(seoul_tz).strftime("%Y-%m-%d")
file_path = f"/content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/테스트데이터/({today})테스트.csv"

test.to_csv(file_path, index=False)
print("✅ 저장 완료:", file_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ 저장 완료: /content/drive/Othercomputers/내 Mac/Desktop/hateslop/프로젝트/테스트데이터/(2025-05-30)테스트.csv